#!/usr/bin/perl

# amcorn

use strict;
use warnings;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;
use Util;

my $username = $ENV{'USER'} || $ENV{'USERNAME'} || getpwuid($<);

if (defined $ARGV[0] and $ARGV[0] =~ /about/i){
  print "Returns current AmCORN price.\n";
  exit 0;
}

my $ua = "Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0";

my $url = "https://markets.businessinsider.com/commodities/corn-price?op=1";
open(HTTP, '-|', "curl -A '$ua' --max-time 10 -s -L --insecure '$url' | grep -A4 'price-section__current-value' | head -1");
binmode(HTTP, ":utf8");
while ( my $line = <HTTP>) {
  if ($line =~ /.+?([0-9.]+).+?$/) {
    my $price = "AmCORN 🌽 $1";
    print $price, "\n";
  }
  chomp $line;
}
close(HTTP);

exit 0;
