#!/usr/bin/perl -w
#
# 2-clause BSD license.
# Copyright (c) 2026 molo1134@github. All rights reserved.

use strict;
use utf8;
use feature 'unicode_strings';
binmode(STDOUT, ":utf8");
use Encode qw(decode);
use I18N::Langinfo qw(langinfo CODESET);
use JSON qw( decode_json );
use URI::Escape;
use Math::Round;
use POSIX qw(floor);
use POSIX qw(strftime);
use POSIX qw(tzset);
use Time::Piece ();

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;
use Location;
use Util;

STDOUT->autoflush();
STDERR->autoflush();

my $username = $ENV{'USER'} || $ENV{'USERNAME'} || getpwuid($<);

# change this to 0 to always exit with success
our $exitnonzeroonerror = 1;
$exitnonzeroonerror = 0 if $username eq getEggdropUID();

our $cacheFile = $ENV{'HOME'} . "/.qrmbot/cache/amtrak-stations.gz";
my $url = "https://asm-backend.transitdocs.com/map";
my $trainId;

my $i = 0;
while ($i <= $#ARGV) {
  if ($ARGV[$i] =~ /--help/) {
    print "usage: amtrak <train number>\n";
    exit $exitnonzeroonerror;
  } elsif ($ARGV[$i] =~ /^[0-9]+$/) {
    $trainId = $ARGV[$i];
  } else {
    print "unknown parameter: $ARGV[$i]";
    exit $exitnonzeroonerror;
  }
  $i++;
}

if (not defined $trainId) {
    print "usage: amtrak <train number>\n";
    exit $exitnonzeroonerror;
}

updateAmtrakStations();

open(CACHE, '-|', "gzip -d < $cacheFile");
local $/;   # read entire file -- FIXME: potentially memory hungry
my $json = <CACHE>;
close(CACHE);

if (not $json =~ /^\s*\[/) {
  print "error while reading cache file: ", substr($json, 0, 60), "\n";
  exit $exitnonzeroonerror;
}

my $stations = decode_json($json);


open(HTTP, '-|', "curl --stderr - --max-time 10 -s -k -L '$url'");
local $/;   # read entire file -- FIXME: potentially memory hungry
$json = <HTTP>;
close(HTTP);

if (not $json =~ /^\s*\[/) {
  print "error while retrieving data: ", substr($json, 0, 60), "\n";
  exit $exitnonzeroonerror;
}

my $j = decode_json($json);

$i = 0;
my $found = 0;

while (defined $j->[$i]) {
  my $number = $j->[$i]->{number};
  if (defined $number and $number == $trainId) {
    $found = 1;
    my $rec = $j->[$i];

    my ($lat, $lon) = ($rec->{location}->{latitude}, $rec->{location}->{longitude});
    my $grid = coordToGrid($lat, $lon);
    my $loc = geolocate($lat, $lon);
    my $speed_mph = round($rec->{location}->{speed});
    my $total_mi = $rec->{total_miles};
    print "$rec->{railroad} #$number ($rec->{origin} -> $rec->{destination}) -- $speed_mph mph in $loc ($grid)";

    $ENV{TZ} = $rec->{current_timezone};
    tzset;

    if (defined $rec->{stops}) {
      foreach my $srec (@{$rec->{stops}}) {
	if (defined $srec->{arrive} and $srec->{arrive}->{type} eq "ESTIMATED") {
	  my $sched_arrive = $srec->{sched_arrive};
	  my $variance = $srec->{arrive}->{variance};
	  my $est_arrive = $sched_arrive - $variance if defined $sched_arrive; # sign reversed
	  my $time = strftime("%Y-%m-%d %H:%M %Z", localtime(int($est_arrive))) if defined $sched_arrive;
	  $time = "" if not defined $sched_arrive;
	  my $relative = sprintf("%s%dh %dm",
				 ($time eq "" ? "" : ", "),
				 abs($variance) / 3600,
				 (abs($variance) % 3600) / 60);
	  $relative .= " early" if $variance > 0;
	  $relative .= " late" if $variance < 0;
	  $relative = "" if $variance == 0;
	  my $stationRec = getRecForStation($srec->{code}, $stations);
	  my $stationDesc = "$stationRec->{city}, $stationRec->{state}";
	  print " -- next stop: $srec->{code}, $stationDesc (mile marker $srec->{miles}";
	  printf(", %d%% of journey)", round(($srec->{miles} / $total_mi) * 100.0));
	  print ", estimated $time$relative" if $time ne "" or $relative ne "";
	  last;
	}
      }
    }
    print "\n";

    if (defined $rec->{alerts}) {
      print yellow("  Alert: "), $rec->{alerts}->[0]->{text}, "\n";
      # only print one
    }
  }
  $i++;
}

print "$trainId not found\n" if not $found;
exit $exitnonzeroonerror if not $found;


sub updateAmtrakStations {
  my $url = "https://asm-backend.transitdocs.com/stationInfo";
  our $cacheFile;

  my $needSta = 0;
  my $now = time;
  my $maxage = 604800; # 1 week
  if (not -e $cacheFile) {
    $needSta = 1
  } else {
    my (undef, undef, undef, undef, undef, undef, undef, $size, undef, $mtime, undef, undef, undef) = stat $cacheFile;
    if (defined $mtime) {
      my $age = $now - $mtime;
      if ($age > $maxage or $size < 1024) {
	$needSta = 1;
      }
    } else {
      $needSta = 1;
    }
  }
  if ($needSta == 1) {
    #print "$url\n";
    system("curl --stderr - -s -k -L --max-time 20 --retry 1 '$url' | gzip -c > '$cacheFile' ");
  }
}


sub getRecForStation {
  my $sta = shift;
  my $stations = shift;

  my $i = 0;
  while (defined $stations->[$i]) {
    if ($stations->[$i]->{code} eq $sta) {
      return $stations->[$i];
    }
    $i++;
  }
  return undef;
}
