#!/usr/bin/perl
#
# argentine peso
#
# 2-clause BSD license.
# Copyright (c) 2023 molo1134@github. All rights reserved.

use strict;
use warnings;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;
use Util;

my $username = $ENV{'USER'} || $ENV{'USERNAME'} || getpwuid($<);

if (defined $ARGV[0] and $ARGV[0] =~ /about/i){
  print "Returns informal 'Dolar Blue' ARS/USD price.\n";
  exit 0;
}

my $url = 'https://bluedollar.net/informal-rate/';
open(HTTP, '-|', "curl --max-time 10 -s -L --insecure '$url' ");
binmode(HTTP, ":utf8");
while (<HTTP>) {
  chomp;
  if (m|<div class="buy buy-sell-blue"><span class="font-number">([0-9,.+-]+)<small>,([0-9]+)</small></span><br>.*?<div class="sell buy-sell-blue"><span class="font-number">([0-9,.+-]+)<small>,([0-9]+)</small></span><br>|) {
    my ($buyprice, $sellprice) = (($1 * 1000.0) + ($2 / 100.0), ($3 * 1000.0) + $4 / 100.0);
    print "buy $buyprice / sell $sellprice USDARS 'Informal Price'\n";
    last;
  }
}
close(HTTP);

exit 0;

