#!/usr/bin/perl -w

# coax loss estimates

use strict;
use utf8;
use feature 'unicode_strings';
binmode(STDOUT, ":utf8");

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Util;
use Colors;

use Math::Round;

my %loss; # dB per 100 ft

my @lossMHz       = (    1,    10,   30,    50,   100,   146,   150,   200,    220,   400,   440,   450,   700,   900,  1000,  1500,  2400);
#-------------------------------------------------------------------------------------------------------
# from universal-radio.com
$loss{"LMR-100A"} = [undef, undef,   3.9,   5.1, undef,   8.8,   8.9, undef, undef, undef,  15.6,  15.8, undef, undef, undef, undef, undef];
$loss{"RG-59"}    = [undef, undef, undef,   2.4,   3.5, undef, undef, undef, undef, undef,   7.6, undef, undef, undef,  12.0, undef, undef];
$loss{"RG-8"}     = [undef, undef, undef,   1.2,   1.8, undef, undef, undef, undef, undef, undef, undef, undef, undef,   7.1, undef, undef];
$loss{"RG-214"}   = [undef, undef,   1.2,   1.6,   1.9,   2.8,   2.8, undef, undef, undef,   5.1,   5.1, undef, undef,   8.0, undef,  13.7];
$loss{"DRF-400"}  = [undef, undef,   0.7,   0.9, undef,   1.5, undef, undef, undef, undef, undef,   2.7, undef, undef, undef, undef,   6.7];
$loss{"Bury-FLEX"}= [undef, undef, undef,   1.1,   1.5, undef, undef, undef, undef, undef, undef, undef, undef, undef,   4.8, undef, undef];
$loss{"9086"}     = [undef, undef, undef, undef,   1.4, undef, undef, undef, undef, undef,   2.8,   2.8, undef, undef, undef, undef, undef];

# from w4rp.com
$loss{"LMR-1200"} = [undef, undef,  0.21,  0.27, undef, undef,  0.48, undef,  0.59, undef, undef,  0.86, undef,  1.27, undef,  1.69, undef];
$loss{"LMR-900"}  = [undef, undef,  0.29,  0.37, undef, undef,  0.66, undef,  0.80, undef, undef,  1.17, undef,  1.70, undef,  2.24, undef];
$loss{"LMR-600"}  = [undef, undef,  0.42,  0.55, undef, undef,  0.96, undef,  1.18, undef, undef,  1.72, undef,  2.50, undef,  3.31, undef];
$loss{"Superflex"}= [undef, undef,  0.56,  0.73, undef, undef,  1.29, undef,  1.58, undef, undef,  2.32, undef,  3.41, undef,  4.57, undef]; # half inch
$loss{"LMR-195"}  = [undef, undef,   1.8,   2.3, undef, undef,   4.0, undef,   4.8, undef, undef,   7.0, undef,   9.9, undef,  12.9, undef];

$loss{"RG-6"}     = [  0.2,   0.6, undef,   1.4,   2.0, undef, undef,   2.8, undef,   4.3, undef, undef,   5.6,   6.0,   6.1, undef, undef];
$loss{"RG-11"}    = [  0.2,   0.4, undef,   1.0,   1.6, undef, undef,   2.3, undef,   3.5, undef, undef,   4.7,   5.4,   5.6, undef, undef];

# considated between w4rp.com and universal-radio.com
$loss{"LMR-200"}  = [undef, undef,   1.8,   2.3, undef,   3.0,   4.0, undef,   4.8, undef,   6.0,   7.0, undef,   9.9, undef,  12.7,  16.5];
$loss{"LMR-240"}  = [undef, undef,   1.3,   1.7, undef,   3.0,   3.0, undef,   3.7, undef,   5.2,   5.3, undef,   7.6, undef,   9.9,  12.7];
$loss{"LMR-400"}  = [undef, undef,   0.7,   0.9, undef,   1.5,   1.5, undef,   1.8, undef,   2.7,   2.7, undef,   3.9, undef,   5.1,   6.6];

$loss{"RG-174"}   = [  1.9,   3.3,   5.5,   6.6,   8.9,  13.0, undef,  11.9, undef,  17.3,  25.0, undef,  26.0,  27.9,  32.0, undef,  75.0];
$loss{"RG-58/U"}  = [  0.4,   1.4,   2.5,   4.1,   5.3,   6.1,   6.2,   7.3,   7.4,  11.2,  10.4,  10.6,  16.9,  20.1,  24.0, undef,  38.9]; # sources disagree
$loss{"RG-8X"}    = [  0.5,   1.0,   2.0,   2.5,   3.6,   4.5,   4.7,   5.4,   6.0,   7.9,   8.1,   8.6,  11.0,  12.8,  13.5, undef,  21.6];
$loss{"RG-213"}   = [  0.2,   0.6, undef,   1.6,   2.2,   2.8,   2.8, undef, undef,   4.8,   5.1,   5.1,   6.6,   7.7,   8.3, undef, undef];
$loss{"9914"}     = [  0.3,   0.5,   0.8,   1.1,   1.5, undef,   1.7,   1.8,   2.1,   2.9, undef,   3.1,   3.8,   4.9,   5.3, undef, undef];
$loss{"9913"}     = [  0.2,   0.4,   0.8,   1.1,   1.4,   1.5,   1.7, undef,   2.1,   2.6,   2.8,   3.1,   3.6,   4.4,   4.5,   6.0,   7.5];

my %imp;
$imp{"RG-6"}      = 75;
$imp{"RG-11"}     = 75;
$imp{"RG-59"}     = 75;

$imp{"9086"}      = 50;
$imp{"9913"}      = 50;
$imp{"9914"}      = 50;
$imp{"Bury-FLEX"} = 50;
$imp{"DRF-400"}   = 50;
$imp{"LMR-100A"}  = 50;
$imp{"LMR-1200"}  = 50;
$imp{"LMR-195"}   = 50;
$imp{"LMR-200"}   = 50;
$imp{"LMR-240"}   = 50;
$imp{"LMR-400"}   = 50;
$imp{"LMR-600"}   = 50;
$imp{"LMR-900"}   = 50;
$imp{"RG-174"}    = 50;
$imp{"RG-213"}    = 50;
$imp{"RG-214"}    = 50;
$imp{"RG-58/U"}   = 50;
$imp{"RG-8"}      = 50;
$imp{"RG-8X"}     = 50;
$imp{"Superflex"} = 50;

# disable "experimental" warning on smart match operator use
no if $] >= 5.018, warnings => "experimental::smartmatch";

my $username = $ENV{'USER'} || $ENV{'USERNAME'} || getpwuid($<);

# change this to 0 to always exit with success
our $exitnonzeroonerror = 1;
$exitnonzeroonerror = 0 if $username eq getEggdropUID();



my ($coax, $freq, $freq_units, $len, $len_units);

# eggdrop doesn't split args on spaces
@ARGV=split(' ', join(' ',@ARGV));

my $i = 0;
while ($i <= $#ARGV) {
  #print "$i: $ARGV[$i]\n";
  if (not defined $coax) {
    $coax = $ARGV[$i];
    $i++;
    next;
  }
  if (defined $coax and not defined $freq) {
    $freq = $ARGV[$i];
    $freq_units = $ARGV[$i+1];
    $i += 2;
    next;
  }
  if (defined $freq and not defined $len) {
    $len = $ARGV[$i];
    $len_units = $ARGV[$i+1];
    $i += 2;
    next;
  }
  print "warning: ignoring extraneous parameters\n";
  $i++;
}

if (defined $coax and defined $freq and defined $freq_units and not defined $len and not defined $len_units) {
  # default to 100 ft
  $len = 100;
  $len_units = "ft";
}

if (defined $coax and (not defined $freq or not defined $len or not defined $freq_units or not defined $len_units)) {
  # display the attenuation table
  my @types = keys %loss;
  my $uc_coax = uc $coax;
  if (not $coax ~~ @types and not $uc_coax ~~ @types) {
    print "Unable to find coax type \"$coax\". Valid types: ", join(", ", sort keys %loss), "\n";
    exit $exitnonzeroonerror;
  }
  $coax = $uc_coax if not defined $loss{$coax};

  print bold($coax), ": ";
  print "\n" if $username ne getEggdropUID();
  for (my $i = 0; $i <= $#lossMHz; $i++) {
    if (defined $loss{$coax}[$i]) {
      print "$lossMHz[$i] MHz => $loss{$coax}[$i] dB/100ft";
      if ($username ne getEggdropUID()) {
	print "\n";
      } else {
	print "; ";
      }
    }
  }
  print "\n" if $username eq getEggdropUID();
  exit 0;
}

if (not defined $coax or not defined $freq or not defined $len or not defined $freq_units or not defined $len_units) {
  print "syntax : !atten <coax type> [<freq> <freq units> [<length> <length units>]]\n";
  print "example: !atten LMR-400 446.0 MHz 12.5 m\n";
  exit $exitnonzeroonerror;
}

my @types = keys %loss;
my $uc_coax = uc $coax;
if (not $coax ~~ @types and not $uc_coax ~~ @types) {
  print "Unable to find coax type \"$coax\". Valid types: ", join(", ", sort keys %loss), "\n";
  exit $exitnonzeroonerror;
}

if (not isNumeric($freq)) {
  print "error: frequency must be numeric\n";
  exit $exitnonzeroonerror;
}
if (not isNumeric($len)) {
  print "error: length must be numeric\n";
  exit $exitnonzeroonerror;
}

if ($freq_units eq "GHz") {
  $freq = $freq * 1000;
  $freq_units = "MHz";
}
if ($freq_units eq "kHz") {
  $freq = $freq / 1000.0;
  $freq_units = "MHz";
}
if ($freq_units ne "MHz") {
  print "unsupported frequency units: $freq_units\n";
  exit $exitnonzeroonerror;
}

if (not defined $loss{$coax}) {
  $coax = uc $coax;
}

$i = 0;
while ($i <= $#lossMHz) {
  if (defined $loss{$coax}[$i]) {
    if ($freq < $lossMHz[$i]) {
      print "Error: lowest supported frequency for $coax is $lossMHz[$i] MHz.\n";
      exit $exitnonzeroonerror;
    }
    last;
  }
  $i++;
}

$i = $#lossMHz;
while ($i >= 0) {
  if (defined $loss{$coax}[$i]) {
    if ($lossMHz[$i] < $freq) {
      print "Error: highest supported frequency for $coax is $lossMHz[$i] MHz.\n";
      exit $exitnonzeroonerror;
    }
    last;
  }
  $i--;
}

if ($len < 0.0) {
  print "Invalid length.\n";
  exit $exitnonzeroonerror;
}

$i = 0;
my ($l, $h);
while ($i <= $#lossMHz) {
  if ($lossMHz[$i] == $freq) {
    $l = $h = $i;
    last;
  }
  if ($lossMHz[$i] <= $freq and $lossMHz[$i+1] > $freq) {
    $l = $i;
    $h = $i+1;
    last;
  }
  $i++;
}

if ($l != $h or not defined $loss{$coax}[$l]) {
  while (not defined $loss{$coax}[$l] and $l > 0) {
    $l--;
  }
  while (not defined $loss{$coax}[$h] and $h <= $#lossMHz) {
    $h++;
  }
}

#print "$lossMHz[$l] ≤ $freq ≤ $lossMHz[$h]\n";
#print "$loss{$coax}[$l] ≤ $loss{$coax}[$h]\n";

# linear interpolation
my $freq_fraction = 1.0;
$freq_fraction = ($freq - $lossMHz[$l]) / ($lossMHz[$h] - $lossMHz[$l]) if $h != $l;
my $atten = (($loss{$coax}[$h] - $loss{$coax}[$l]) * $freq_fraction) + $loss{$coax}[$l];

open (UNITS, '-|', "units --compact '$len $len_units / 100 ft'");
my $len_fraction = <UNITS>;
close(UNITS);
if (not isNumeric($len_fraction)) {
  print "$len_fraction";
  exit $exitnonzeroonerror;
}

my $atten_at_len = nearest(0.01, $len_fraction * $atten);
my $atten_m = nearest (0.01, $atten * 3.2808399); # 3.28 ft/m
$atten = nearest(0.01, $atten);

print "$coax ($imp{$coax}Ω) attenuation estimated at $freq $freq_units: $atten dB/100 ft ($atten_m dB/100 m); loss \@length $len $len_units: ", bold("$atten_at_len dB"), "\n";
