#!/usr/bin/perl -w
# Report cryptocurrency prices.

# 2-clause BSD license.
# Copyright (c) 2018, 2019, 2020, 2021 molo1134@github. All rights reserved.

use strict;
use utf8;
use feature 'unicode_strings';
binmode(STDOUT, ":utf8");
use Math::Round;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;
use Util;

our $coinmarketcapkey = undef;
my $coinmarketcapfile = $ENV{'HOME'} . "/.coinmarketcapkey";
if (-e ($coinmarketcapfile)) {
  require($coinmarketcapfile);
}

print "error: unable to get api key from $coinmarketcapfile\n" if not defined $coinmarketcapkey;
exit 1 if not defined $coinmarketcapkey;

my $fiat = undef;

# eggdrop doesn't split args on spaces
@ARGV=split(' ', join(' ',@ARGV));

my $crypto = undef;

my $i = 0;
while ($i <= $#ARGV) {
  # list comes from here: https://coinmarketcap.com/api/
  if (uc($ARGV[$i]) =~ /^(AUD|BRL|CAD|CHF|CLP|CNY|CZK|DKK|EUR|GBP|HKD|HUF|IDR|ILS|INR|JPY|KRW|MXN|MYR|NOK|NZD|PHP|PKR|PLN|RUB|SEK|SGD|THB|TRY|TWD|USD|ZAR)$/i) {
    $fiat = uc $1;
  } else {
    $crypto = uc($ARGV[$i]);
  }
  $i++;
}

$crypto = "BTC" unless defined($crypto);
$fiat = "USD" unless defined($fiat);

$crypto =~ s/[^A-Z]//g;
$fiat =~ s/[^A-Z]//g;

if ($crypto =~ /CUMMIES/i) {
  print "nope\n";
  exit 0;
}

# example: https://api.coinmarketcap.com/v1/ticker/bitcoin/?convert=USD
#my $url = "https://api.coinmarketcap.com/v1/ticker/$id/?convert=$fiat";
#my $url = "http://35.194.32.186:8018/phpproxy/coinmarketcap-proxy.php?id=$id&fiat=$fiat";
my $url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?CMC_PRO_API_KEY=$coinmarketcapkey&symbol=$crypto&convert=$fiat";
my %results;

#print "$url\n";
open(HTTP, '-|', "curl --max-time 5 -s -k -L -H 'Accept: application/json' '$url' | jq . ");
binmode(HTTP, ":utf8");
while (<HTTP>) {
  #print;
  if (/"data": \{}/) {
    print "error: no result\n";
    exit 0;
  }
  if (/"(\w+)":\s*"?(.*?)"?,?\s*$/) {
    my ($key, $value) = ($1, $2);
    $results{$key} = $value;
    #print "$key :: $value\n";
    if ($key eq "error_message" and $value ne "null") {
      print "error: $value\n";
      exit 0;
    }
  }
}
close(HTTP);

my $target = lc($fiat);

my ($volume, $mktcap, $qty);
$qty = 0;
$volume = humanNum(int($results{"volume_24h"})) if defined $results{"volume_24h"};
$mktcap = humanNum(int($results{"market_cap"})) if defined $results{"market_cap"} and $results{"market_cap"} ne "null";
$mktcap = "" if not defined $mktcap;
$qty = int ($results{"volume_24h"} / $results{"price"}) if defined $results{"price"} and defined $results{"volume_24h"};
$results{"price"} = commify($results{"price"}) if defined($results{"price"});

my $trendsymbol;
my $trend = $results{percent_change_24h};
$trendsymbol = green("↑") if defined $trend and $trend ne "null" and $trend > 0.0;
$trendsymbol = red("↓") if defined $trend and $trend ne "null" and $trend < 0.0;
$trendsymbol = "·" if !defined $trendsymbol;
if (defined $trend and $trend ne "null") {
  if ($trend < 0) {
    $trend = red(nearest(0.1, $trend));
  } elsif ($trend > 0) {
    $trend = green("+" . nearest(0.1, $trend));
  }
} else {
  $trend = "??"
}
$volume = 0 if not defined $volume;

print bold("$crypto$fiat"). " $trendsymbol" . $results{"price"} . " $trend% qty " . humanNum($qty) . " $crypto/24h ($volume $fiat/24h) MktCap $mktcap $fiat\n";

exit 0;

