#!/usr/bin/perl
#
# 2-clause BSD license.
# Copyright (c) 2018, 2019, 2020, 2021 molo1134@github. All rights reserved.

# put the following in $HOME/.qrmbot/keys/clublog to use the log search:
#
#our $apikey="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;
use Util;

use JSON qw( decode_json );
use File::Temp qw(tempfile);
use strict;

my $url = 'https://clublog.org/clublog-users.json.zip';
my $userfile=$ENV{'HOME'} . "/.clublogusers.gz";
my $maxage=604800; # 1 week
my $username = $ENV{'USER'} || $ENV{'USERNAME'} || getpwuid($<);

# change this to 0 to always exit with success
my $exitnonzeroonerror = 1;
$exitnonzeroonerror = 0 if $username eq getEggdropUID();

sub updatezip {
  my (undef, $tmpfile) = tempfile();
  system "curl --max-time 10 -s -k -L -o $tmpfile '$url'";
  system "unzip -p $tmpfile clublog_users.json | gzip -c > $userfile";
  unlink $tmpfile;
}

our $apikey = undef;
my $newApikeyfile = $ENV{'HOME'} . "/.qrmbot/keys/clublog";
my $oldApikeyfile = $ENV{'HOME'} . "/.clublogapikey";
moveFile($oldApikeyfile, $newApikeyfile);
if (-e ($newApikeyfile)) {
  require($newApikeyfile);
} elsif (-e $oldApikeyfile) { # fallback
  require($oldApikeyfile);
} else {
  die "error: unable to read file $newApikeyfile"
}

if ($#ARGV < 0 || length($ARGV[0]) == 0) {
  if ($username eq getEggdropUID()) {
    print "usage: !clublog <callsign> [logged call]\n";
  } else {
    print "usage: $0 <callsign> [logged call]\n";
  }
  exit $exitnonzeroonerror;
}

my $call = uc $ARGV[0];
$call =~ s/^\s*//;
$call =~ s/\s*$//;

my $call2 = undef;
if ($#ARGV >= 1) {
  $call2 = uc $ARGV[1];
  $call2 =~ s/^\s*//;
  $call2 =~ s/\s*$//;
}

if (defined $call2) {
  our $apikey;
  my $url = "https://clublog.org/logsearchjson.php?log=${call}&call=${call2}&api=$apikey";
  local $/;   # read entire file -- FIXME: potentially memory hungry
  open(JSON, '-|', "curl -k -L --max-time 10 --retry 1 -s '$url'");
  my $json = <JSON>;
  close(JSON);
  #print "$json\n";
  if ($json =~ /is not registered on Club Log/) {
    print "$call not registered on clublog\n";
    exit 0;
  }
  my $j = decode_json($json);
  if (ref($j) ne 'HASH') {
    print "$call2 not found in $call clublog\n";
    exit 0;
  } 
  print bold($call2), " in ", bold($call), " clublog: ";
  print "\n" if $username ne getEggdropUID();
  my @digi;
  my @morse;
  my @phone;
  foreach my $band (%{$j}) {
    my ($ph, $cw, $dt) = (0,0,0);
    next if not defined $j->{$band};
    $ph = $j->{$band}->{P} if defined $j->{$band}->{P};
    $cw = $j->{$band}->{C} if defined $j->{$band}->{C};
    $dt = $j->{$band}->{D} if defined $j->{$band}->{D};

    push @phone, $band if $ph > 0;
    push @digi, $band if $dt > 0;
    push @morse, $band if $cw > 0;
  }

  # sort
  @phone = sort { $b <=> $a } @phone;
  @morse = sort { $b <=> $a } @morse;
  @digi = sort { $b <=> $a } @digi;

  if (scalar @phone > 0) {
    print " Phone: ", join(",", @phone);

    print "\n" if $username ne getEggdropUID();
    print ";" if $username eq getEggdropUID();
  }

  if (scalar @morse > 0) {
    print " CW: ", join(",", @morse);

    print "\n" if $username ne getEggdropUID();
    print ";" if $username eq getEggdropUID();
  }

  if (scalar @digi > 0) {
    print " Digital: ", join(",", @digi);
  }

  print "\n";
  exit 0;
}

my $now = time;
my $needzip = 0;
if ( ! -e $userfile ) {
  $needzip = 1;
} else {
  my (undef, undef, undef, undef, undef, undef, undef, $size, undef, $mtime, undef, undef, undef) = stat $userfile;
  if (defined $mtime) {
    my $age = $now - $mtime;
    if ($age > $maxage or $size == 0) {
      $needzip = 1;
    }
  } else {
    $needzip = 1;
  }
}

updatezip() if ($needzip == 1);

my %rec;

local $/;   # read entire file -- FIXME: potentially memory hungry
open (GZIP, '-|', "gzip -dc $userfile") or die "Can't open for reading: $!";
binmode(GZIP, ":utf8");
my $json = <GZIP>;
close(GZIP);
my $j = decode_json($json) or die "parse error: $json\n";
if (defined ($j->{$call})) {
  %rec = %{$j->{$call}};
}


#print scalar(keys(%rec)), "\n";
#print join (" ", keys(%rec)), "\n";
#foreach my $k (keys %rec) {
#  my $v = $rec{$k};
#  $v = "undef" if not defined $v;
#  print "$k => $v\n";
#}

# get latest qso start and end dates from the API, because zip file is old
our $apikey;
my $url = "https://clublog.org/logcheck.php?call=${call}&api=${apikey}";

local $/;   # read entire file -- FIXME: potentially memory hungry
open(HTTP, '-|', "curl -k -L --max-time 10 --retry 1 -s '$url'");
my $output = <HTTP>;
close(HTTP);
#print "$output\n";
if ($output =~ /Callsign not valid or not registered in Club Log/) {
  print "$call not found on clublog\n";
  exit 0;
}
if ($output =~ /\["([0-9-]+\s+[0-9:]+)",\s*"([0-9-]+\s+[0-9:]+)"\]/) {
  $rec{firstqso} = $1;
  $rec{lastqso} = $2;
}

# firstqso 1995-08-09 23:09:00
# lastqso 2018-07-01 13:09:00
# lastupload 2018-08-16 22:53:01
# locator JO02AE
# oqrs 0

my ($start, undef) = split(" ",$rec{firstqso});
my ($end, undef) = split(" ",$rec{lastqso});
my ($upload, undef) = split(" ", $rec{lastupload}) if defined $rec{lastupload};

$upload = "${end}?" if defined $upload and $upload lt $end;

print bold($call), ": ";
print "clublog from $start to $end" if defined $start or defined $end;
print "no clublog logs" if not defined $start and not defined $end;
print "; last upload $upload" if defined $upload;
print "; " . bold("OQRS") if $rec{oqrs} eq "true" or $rec{oqrs} == 1;
print "; grid $rec{locator}" if defined $rec{locator};
print "\n";

exit 0;
