#!/usr/bin/perl

# coronavirus info for qrmbot
# initial version by aa4jq
# modified by k2cr
#
# 2-clause BSD license.
#
# Copyright (c) 2020 AA4JQ. All rights reserved.
# Copyright (c) 2020, 2021 molo1134@github. All rights reserved.

use strict;
use utf8;
use feature 'unicode_strings';
binmode(STDOUT, ":utf8");
use Encode qw(decode);
use I18N::Langinfo qw(langinfo CODESET);
use JSON qw( decode_json );

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Util;
use Colors;

use Math::Round;
use List::Util qw(sum min max);
use Clone qw(clone);

# disable "experimental" warning on smart match operator use
no if $] >= 5.018, warnings => "experimental::smartmatch";

if ($ARGV[0] =~ /about/i){
  print "Covid19 case counts.  Data sources: https://github.com/CSSEGISandData/COVID-19 https://github.com/nytimes/covid-19-data/ https://github.com/jgehrcke/covid-19-germany-gae https://www.worldometers.info/coronavirus/ https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations https://covid.cdc.gov/covid-data-tracker/#county-view https://www.economist.com/graphic-detail/coronavirus-excess-deaths-estimates\n";

  my @casespercap = ( 1.0, 5.0, 25.0, 38.0, 50.0, 100.0, 325.0 );
  my @result = seriesToSparkLine(\@casespercap, 1, 0);
  my $min = $result[0];
  my $max = $result[1];
  my @spark = @result[2 .. $#result];
  printf " sparkline colored by per-capita case counts: %s - %s,%s,%s,%s,%s,%s,%s cases per 100k population over 7 days\n", join("", @spark),
    colorByRate("<5", 1),
    colorByRate("5", 5),
    colorByRate("25", 25),
    colorByRate("38", 38),
    colorByRate("50", 50),
    colorByRate("100", 100),
    colorByRate(">325", 325);


  exit 0;
}

my $args = join(" ", @ARGV);

# decode command line from locale-specified codeset
my $codeset = langinfo(CODESET);
$args = decode($codeset, $args);

# eggdrop doesn't split args on spaces
@ARGV = split(' ', $args);

my @interest;
my @states;

my @statesandterritories = ("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE",
  "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA",
  "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND",
  "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA",
  "WV", "WI", "WY", "DC", "GU", "AS", "MP", "PR", "VI", "UM", "FM", "MH", "PW",
  "AA", "AE", "AP");

my %stateToName;
$stateToName{US} = "National";
$stateToName{AK} = "Alaska";
$stateToName{AL} = "Alabama";
$stateToName{AR} = "Arkansas";
$stateToName{AZ} = "Arizona";
$stateToName{CA} = "California";
$stateToName{CO} = "Colorado";
$stateToName{CT} = "Connecticut";
$stateToName{DC} = "District of Columbia";
$stateToName{DE} = "Delaware";
$stateToName{FL} = "Florida";
$stateToName{GA} = "Georgia";
$stateToName{HI} = "Hawaii";
$stateToName{IA} = "Iowa";
$stateToName{ID} = "Idaho";
$stateToName{IL} = "Illinois";
$stateToName{IN} = "Indiana";
$stateToName{KS} = "Kansas";
$stateToName{KY} = "Kentucky";
$stateToName{LA} = "Louisiana";
$stateToName{MA} = "Massachusetts";
$stateToName{MD} = "Maryland";
$stateToName{ME} = "Maine";
$stateToName{MI} = "Michigan";
$stateToName{MN} = "Minnesota";
$stateToName{MO} = "Missouri";
$stateToName{MS} = "Mississippi";
$stateToName{MT} = "Montana";
$stateToName{NC} = "North Carolina";
$stateToName{ND} = "North Dakota";
$stateToName{NE} = "Nebraska";
$stateToName{NH} = "New Hampshire";
$stateToName{NJ} = "New Jersey";
$stateToName{NM} = "New Mexico";
$stateToName{NV} = "Nevada";
$stateToName{NY} = "New York";
$stateToName{OH} = "Ohio";
$stateToName{OK} = "Oklahoma";
$stateToName{OR} = "Oregon";
$stateToName{PA} = "Pennsylvania";
$stateToName{RI} = "Rhode Island";
$stateToName{SC} = "South Carolina";
$stateToName{SD} = "South Dakota";
$stateToName{TN} = "Tennessee";
$stateToName{TX} = "Texas";
$stateToName{UT} = "Utah";
$stateToName{VA} = "Virginia";
$stateToName{VT} = "Vermont";
$stateToName{WA} = "Washington";
$stateToName{WI} = "Wisconsin";
$stateToName{WV} = "West Virginia";
$stateToName{WY} = "Wyoming";

$stateToName{PR} = "Puerto Rico";
$stateToName{GU} = "Guam";
$stateToName{VI} = "Virgin Islands";
$stateToName{MP} = "Northern Mariana Islands";

my %statePop;
# 2020 state populations
$statePop{AK} = 736081;
$statePop{AL} = 5030053;
$statePop{AR} = 3013756;
$statePop{AZ} = 7158923;
$statePop{CA} = 39576757;
$statePop{CO} = 5782171;
$statePop{CT} = 3608298;
$statePop{DE} = 990837;
$statePop{FL} = 21570527;
$statePop{GA} = 10725274;
$statePop{HI} = 1460137;
$statePop{IA} = 3192406;
$statePop{ID} = 1841377;
$statePop{IL} = 12822739;
$statePop{IN} = 6790280;
$statePop{KS} = 2940865;
$statePop{KY} = 4509342;
$statePop{LA} = 4661468;
$statePop{MA} = 7033469;
$statePop{MD} = 6185278;
$statePop{ME} = 1363582;
$statePop{MI} = 10084442;
$statePop{MN} = 5709752;
$statePop{MO} = 6160281;
$statePop{MS} = 2963914;
$statePop{MT} = 1085407;
$statePop{NC} = 10453948;
$statePop{ND} = 779702;
$statePop{NE} = 1963333;
$statePop{NH} = 1379089;
$statePop{NJ} = 9294493;
$statePop{NM} = 2120220;
$statePop{NV} = 3108462;
$statePop{NY} = 20215751;
$statePop{OH} = 11808848;
$statePop{OK} = 3963516;
$statePop{OR} = 4241500;
$statePop{PA} = 13011844;
$statePop{RI} = 1098163;
$statePop{SC} = 5124712;
$statePop{SD} = 887770;
$statePop{TN} = 6916897;
$statePop{TX} = 29183290;
$statePop{UT} = 3275252;
$statePop{VA} = 8654542;
$statePop{VT} = 643503;
$statePop{WA} = 7715946;
$statePop{WI} = 5897473;
$statePop{WV} = 1795045;
$statePop{WY} = 577719;

# 2019 census population estimate
$statePop{MP} = 55194;
$statePop{AS} = 55641;
$statePop{VI} = 104914;
$statePop{GU} = 165718;
$statePop{DC} = 705749;
$statePop{PR} = 3193694;

my %countryPop;
my %countryName;
my %economist_name;
# source: http://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=json&per_page=500&date=2019
$countryPop{EUU} = 447512041;
$countryName{EUU} = "European Union";
$countryPop{WLD} = 7673533972;
$countryName{WLD} = "World";
$countryPop{AFG} = 38041754;
$countryName{AFG} = "Afghanistan";
$countryPop{ALB} = 2854191;
$countryName{ALB} = "Albania";
$countryPop{DZA} = 43053054;
$countryName{DZA} = "Algeria";
$countryPop{ASM} = 55312;
$countryName{ASM} = "American Samoa";
$countryPop{AND} = 77142;
$countryName{AND} = "Andorra";
$countryPop{AGO} = 31825295;
$countryName{AGO} = "Angola";
$countryPop{ATG} = 97118;
$countryName{ATG} = "Antigua and Barbuda";
$countryPop{ARG} = 44938712;
$countryName{ARG} = "Argentina";
$countryPop{ARM} = 2957731;
$countryName{ARM} = "Armenia";
$countryPop{ABW} = 106314;
$countryName{ABW} = "Aruba";
$countryPop{AUS} = 25364307;
$countryName{AUS} = "Australia";
$countryPop{AUT} = 8877067;
$countryName{AUT} = "Austria";
$countryPop{AZE} = 10023318;
$countryName{AZE} = "Azerbaijan";
$countryPop{BHS} = 389482;
$countryName{BHS} = "Bahamas";
$countryPop{BHR} = 1641172;
$countryName{BHR} = "Bahrain";
$countryPop{BGD} = 163046161;
$countryName{BGD} = "Bangladesh";
$countryPop{BRB} = 287025;
$countryName{BRB} = "Barbados";
$countryPop{BLR} = 9466856;
$countryName{BLR} = "Belarus";
$countryPop{BEL} = 11484055;
$countryName{BEL} = "Belgium";
$countryPop{BLZ} = 390353;
$countryName{BLZ} = "Belize";
$countryPop{BEN} = 11801151;
$countryName{BEN} = "Benin";
$countryPop{BMU} = 63918;
$countryName{BMU} = "Bermuda";
$countryPop{BTN} = 763092;
$countryName{BTN} = "Bhutan";
$countryPop{BOL} = 11513100;
$countryName{BOL} = "Bolivia";
$countryPop{BIH} = 3301000;
$countryName{BIH} = "Bosnia and Herzegovina";
$countryPop{BWA} = 2303697;
$countryName{BWA} = "Botswana";
$countryPop{BRA} = 211049527;
$countryName{BRA} = "Brazil";
$countryPop{VGB} = 30030;
$countryName{VGB} = "British Virgin Islands";
$countryPop{BRN} = 433285;
$countryName{BRN} = "Brunei";
$countryPop{BGR} = 6975761;
$countryName{BGR} = "Bulgaria";
$countryPop{BFA} = 20321378;
$countryName{BFA} = "Burkina Faso";
$countryPop{BDI} = 11530580;
$countryName{BDI} = "Burundi";
$countryPop{CPV} = 549935;
$countryName{CPV} = "Cabo Verde";
$countryPop{KHM} = 16486542;
$countryName{KHM} = "Cambodia";
$countryPop{CMR} = 25876380;
$countryName{CMR} = "Cameroon";
$countryPop{CAN} = 37589262;
$countryName{CAN} = "Canada";
$countryPop{CYM} = 64948;
$countryName{CYM} = "Cayman Islands";
$countryPop{CAF} = 4745185;
$countryName{CAF} = "Central African Republic";
$countryPop{TCD} = 15946876;
$countryName{TCD} = "Chad";
$countryPop{CHI} = 172259;
$countryName{CHI} = "Channel Islands";
$countryPop{CHL} = 18952038;
$countryName{CHL} = "Chile";
$countryPop{CHN} = 1397715000;
$countryName{CHN} = "China";
$countryPop{COL} = 50339443;
$countryName{COL} = "Colombia";
$countryPop{COM} = 850886;
$countryName{COM} = "Comoros";
$countryPop{COD} = 86790567;
$countryName{COD} = "Congo (Kinshasa)";
$countryPop{COG} = 5380508;
$countryName{COG} = "Congo (Brazzaville)";
$countryPop{CRI} = 5047561;
$countryName{CRI} = "Costa Rica";
$countryPop{CIV} = 25716544;
$countryName{CIV} = "Cote d'Ivoire";
$countryPop{HRV} = 4067500;
$countryName{HRV} = "Croatia";
$countryPop{CUB} = 11333483;
$countryName{CUB} = "Cuba";
$countryPop{CUW} = 157538;
$countryName{CUW} = "Curacao";
$countryPop{CYP} = 1198575;
$countryName{CYP} = "Cyprus";
$countryPop{CZE} = 10669709;
$countryName{CZE} = "Czechia";
$countryPop{DNK} = 5818553;
$countryName{DNK} = "Denmark";
$countryPop{DJI} = 973560;
$countryName{DJI} = "Djibouti";
$countryPop{DMA} = 71808;
$countryName{DMA} = "Dominica";
$countryPop{DOM} = 10738958;
$countryName{DOM} = "Dominican Republic";
$countryPop{ECU} = 17373662;
$countryName{ECU} = "Ecuador";
$countryPop{EGY} = 100388073;
$countryName{EGY} = "Egypt";
$countryPop{SLV} = 6453553;
$countryName{SLV} = "El Salvador";
$countryPop{GNQ} = 1355986;
$countryName{GNQ} = "Equatorial Guinea";
#$countryName{ERI} = "Eritrea";
$countryPop{EST} = 1326590;
$countryName{EST} = "Estonia";
$countryPop{SWZ} = 1148130;
$countryName{SWZ} = "Eswatini";
$countryPop{ETH} = 112078730;
$countryName{ETH} = "Ethiopia";
$countryPop{FRO} = 48678;
$countryName{FRO} = "Faroe Islands";
$countryPop{FJI} = 889953;
$countryName{FJI} = "Fiji";
$countryPop{FIN} = 5520314;
$countryName{FIN} = "Finland";
$countryPop{FRA} = 67059887;
$countryName{FRA} = "France";
$countryPop{PYF} = 279287;
$countryName{PYF} = "French Polynesia";
$countryPop{GAB} = 2172579;
$countryName{GAB} = "Gabon";
$countryPop{GMB} = 2347706;
$countryName{GMB} = "Gambia";
$countryPop{GEO} = 3720382;
$countryName{GEO} = "Georgia";
$countryPop{DEU} = 83132799;
$countryName{DEU} = "Germany";
$countryPop{GHA} = 30417856;
$countryName{GHA} = "Ghana";
$countryPop{GIB} = 33701;
$countryName{GIB} = "Gibraltar";
$countryPop{GRC} = 10716322;
$countryName{GRC} = "Greece";
$countryPop{GRL} = 56225;
$countryName{GRL} = "Greenland";
$countryPop{GRD} = 112003;
$countryName{GRD} = "Grenada";
$countryPop{GUM} = 167294;
$countryName{GUM} = "Guam";
$countryPop{GTM} = 16604026;
$countryName{GTM} = "Guatemala";
$countryPop{GIN} = 12771246;
$countryName{GIN} = "Guinea";
$countryPop{GNB} = 1920922;
$countryName{GNB} = "Guinea-Bissau";
$countryPop{GUY} = 782766;
$countryName{GUY} = "Guyana";
$countryPop{HTI} = 11263077;
$countryName{HTI} = "Haiti";
$countryPop{HND} = 9746117;
$countryName{HND} = "Honduras";
$countryPop{HKG} = 7507400;
$countryName{HKG} = "Hong Kong";
$countryPop{HUN} = 9769949;
$countryName{HUN} = "Hungary";
$countryPop{ISL} = 361313;
$countryName{ISL} = "Iceland";
$countryPop{IND} = 1366417754;
$countryName{IND} = "India";
$countryPop{IDN} = 270625568;
$countryName{IDN} = "Indonesia";
$countryPop{IRN} = 82913906;
$countryName{IRN} = "Iran";
$countryPop{IRQ} = 39309783;
$countryName{IRQ} = "Iraq";
$countryPop{IRL} = 4941444;
$countryName{IRL} = "Ireland";
$countryPop{IMN} = 84584;
$countryName{IMN} = "Isle of Man";
$countryPop{ISR} = 9053300;
$countryName{ISR} = "Israel";
$countryPop{ITA} = 60297396;
$countryName{ITA} = "Italy";
$countryPop{JAM} = 2948279;
$countryName{JAM} = "Jamaica";
$countryPop{JPN} = 126264931;
$countryName{JPN} = "Japan";
$countryPop{JOR} = 10101694;
$countryName{JOR} = "Jordan";
$countryPop{KAZ} = 18513930;
$countryName{KAZ} = "Kazakhstan";
$countryPop{KEN} = 52573973;
$countryName{KEN} = "Kenya";
$countryPop{KIR} = 117606;
$countryName{KIR} = "Kiribati";
#$countryPop{PRK} = 25666161;
#$countryName{PRK} = "Korea, Dem. People’s Rep.";
$countryPop{KOR} = 51709098;
$countryName{KOR} = "Korea";
$countryPop{XKX} = 1794248;
$countryName{XKX} = "Kosovo";
$countryPop{KWT} = 4207083;
$countryName{KWT} = "Kuwait";
$countryPop{KGZ} = 6456900;
$countryName{KGZ} = "Kyrgyzstan";
$countryPop{LAO} = 7169455;
$countryName{LAO} = "Laos";
$countryPop{LVA} = 1912789;
$countryName{LVA} = "Latvia";
$countryPop{LBN} = 6855713;
$countryName{LBN} = "Lebanon";
$countryPop{LSO} = 2125268;
$countryName{LSO} = "Lesotho";
$countryPop{LBR} = 4937374;
$countryName{LBR} = "Liberia";
$countryPop{LBY} = 6777452;
$countryName{LBY} = "Libya";
$countryPop{LIE} = 38019;
$countryName{LIE} = "Liechtenstein";
$countryPop{LTU} = 2786844;
$countryName{LTU} = "Lithuania";
$countryPop{LUX} = 619896;
$countryName{LUX} = "Luxembourg";
$countryPop{MAC} = 640445;
$countryName{MAC} = "Macao";
$countryPop{MDG} = 26969307;
$countryName{MDG} = "Madagascar";
$countryPop{MWI} = 18628747;
$countryName{MWI} = "Malawi";
$countryPop{MYS} = 31949777;
$countryName{MYS} = "Malaysia";
$countryPop{MDV} = 530953;
$countryName{MDV} = "Maldives";
$countryPop{MLI} = 19658031;
$countryName{MLI} = "Mali";
$countryPop{MLT} = 502653;
$countryName{MLT} = "Malta";
$countryPop{MHL} = 58791;
$countryName{MHL} = "Marshall Islands";
$countryPop{MRT} = 4525696;
$countryName{MRT} = "Mauritania";
$countryPop{MUS} = 1265711;
$countryName{MUS} = "Mauritius";
$countryPop{MEX} = 127575529;
$countryName{MEX} = "Mexico";
$countryPop{FSM} = 113815;
$countryName{FSM} = "Micronesia";
$countryPop{MDA} = 2657637;
$countryName{MDA} = "Moldova";
$countryPop{MCO} = 38964;
$countryName{MCO} = "Monaco";
$countryPop{MNG} = 3225167;
$countryName{MNG} = "Mongolia";
$countryPop{MNE} = 622137;
$countryName{MNE} = "Montenegro";
$countryPop{MAR} = 36471769;
$countryName{MAR} = "Morocco";
$countryPop{MOZ} = 30366036;
$countryName{MOZ} = "Mozambique";
$countryPop{MMR} = 54045420;
#$countryName{MMR} = "Myanmar";
$countryName{MMR} = "Burma";
$countryPop{NAM} = 2494530;
$countryName{NAM} = "Namibia";
$countryPop{NRU} = 12581;
$countryName{NRU} = "Nauru";
$countryPop{NPL} = 28608710;
$countryName{NPL} = "Nepal";
$countryPop{NLD} = 17332850;
$countryName{NLD} = "Netherlands";
$countryPop{NCL} = 287800;
$countryName{NCL} = "New Caledonia";
$countryPop{NZL} = 4917000;
$countryName{NZL} = "New Zealand";
$countryPop{NIC} = 6545502;
$countryName{NIC} = "Nicaragua";
$countryPop{NER} = 23310715;
$countryName{NER} = "Niger";
$countryPop{NGA} = 200963599;
$countryName{NGA} = "Nigeria";
$countryPop{MKD} = 2083459;
$countryName{MKD} = "North Macedonia";
$countryPop{MNP} = 57216;
$countryName{MNP} = "Northern Mariana Islands";
$countryPop{NOR} = 5347896;
$countryName{NOR} = "Norway";
$countryPop{OMN} = 4974986;
$countryName{OMN} = "Oman";
$countryPop{PAK} = 216565318;
$countryName{PAK} = "Pakistan";
$countryPop{PLW} = 18008;
$countryName{PLW} = "Palau";
$countryPop{PAN} = 4246439;
$countryName{PAN} = "Panama";
$countryPop{PNG} = 8776109;
$countryName{PNG} = "Papua New Guinea";
$countryPop{PRY} = 7044636;
$countryName{PRY} = "Paraguay";
$countryPop{PER} = 32510453;
$countryName{PER} = "Peru";
$countryPop{PHL} = 108116615;
$countryName{PHL} = "Philippines";
$countryPop{POL} = 37970874;
$countryName{POL} = "Poland";
$countryPop{PRT} = 10269417;
$countryName{PRT} = "Portugal";
$countryPop{PRI} = 3193694;
$countryName{PRI} = "Puerto Rico";
$countryPop{QAT} = 2832067;
$countryName{QAT} = "Qatar";
$countryPop{ROU} = 19356544;
$countryName{ROU} = "Romania";
$countryPop{RUS} = 144373535;
$countryName{RUS} = "Russia";
$countryPop{RWA} = 12626950;
$countryName{RWA} = "Rwanda";
$countryPop{WSM} = 197097;
$countryName{WSM} = "Samoa";
$countryPop{SMR} = 33860;
$countryName{SMR} = "San Marino";
$countryPop{STP} = 215056;
$countryName{STP} = "Sao Tome and Principe";
$countryPop{SAU} = 34268528;
$countryName{SAU} = "Saudi Arabia";
$countryPop{SEN} = 16296364;
$countryName{SEN} = "Senegal";
$countryPop{SRB} = 6944975;
$countryName{SRB} = "Serbia";
$countryPop{SYC} = 97625;
$countryName{SYC} = "Seychelles";
$countryPop{SLE} = 7813215;
$countryName{SLE} = "Sierra Leone";
$countryPop{SGP} = 5703569;
$countryName{SGP} = "Singapore";
$countryPop{SXM} = 40733;
$countryName{SXM} = "Sint Maarten (Dutch part)";
$countryPop{SVK} = 5454073;
$countryName{SVK} = "Slovakia";
$countryPop{SVN} = 2087946;
$countryName{SVN} = "Slovenia";
$countryPop{SLB} = 669823;
$countryName{SLB} = "Solomon Islands";
$countryPop{SOM} = 15442905;
$countryName{SOM} = "Somalia";
$countryPop{ZAF} = 58558270;
$countryName{ZAF} = "South Africa";
$countryPop{SSD} = 11062113;
$countryName{SSD} = "South Sudan";
$countryPop{ESP} = 47076781;
$countryName{ESP} = "Spain";
$countryPop{LKA} = 21803000;
$countryName{LKA} = "Sri Lanka";
$countryPop{KNA} = 52823;
$countryName{KNA} = "Saint Kitts and Nevis";
$countryPop{LCA} = 182790;
$countryName{LCA} = "Saint Lucia";
$countryPop{MAF} = 38002;
$countryName{MAF} = "St. Martin (French part)";
$countryPop{VCT} = 110589;
$countryName{VCT} = "Saint Vincent and the Grenadines";
$countryPop{SDN} = 42813238;
$countryName{SDN} = "Sudan";
$countryPop{SUR} = 581372;
$countryName{SUR} = "Suriname";
$countryPop{SWE} = 10285453;
$countryName{SWE} = "Sweden";
$countryPop{CHE} = 8574832;
$countryName{CHE} = "Switzerland";
$countryPop{SYR} = 17070135;
$countryName{SYR} = "Syria";
$countryPop{TWN} = 23603121;   # added from wikipedia  https://en.wikipedia.org/wiki/Demographics_of_Taiwan#Population
$countryName{TWN} = "Taiwan*"; # added
$countryPop{TJK} = 9321018;
$countryName{TJK} = "Tajikistan";
$countryPop{TZA} = 58005463;
$countryName{TZA} = "Tanzania";
$countryPop{THA} = 69625582;
$countryName{THA} = "Thailand";
$countryPop{TLS} = 1293119;
$countryName{TLS} = "Timor-Leste";
$countryPop{TGO} = 8082366;
$countryName{TGO} = "Togo";
$countryPop{TON} = 104494;
$countryName{TON} = "Tonga";
$countryPop{TTO} = 1394973;
$countryName{TTO} = "Trinidad and Tobago";
$countryPop{TUN} = 11694719;
$countryName{TUN} = "Tunisia";
$countryPop{TUR} = 83429615;
$countryName{TUR} = "Turkey";
$countryPop{TKM} = 5942089;
$countryName{TKM} = "Turkmenistan";
$countryPop{TCA} = 38191;
$countryName{TCA} = "Turks and Caicos Islands";
$countryPop{TUV} = 11646;
$countryName{TUV} = "Tuvalu";
$countryPop{UGA} = 44269594;
$countryName{UGA} = "Uganda";
$countryPop{UKR} = 44385155;
$countryName{UKR} = "Ukraine";
$countryPop{ARE} = 9770529;
$countryName{ARE} = "United Arab Emirates";
$countryPop{GBR} = 66834405;
$countryName{GBR} = "United Kingdom";
$countryPop{USA} = 331108434; # 2020
#$countryName{USA} = "United States";
$countryName{USA} = "US";
$countryPop{URY} = 3461734;
$countryName{URY} = "Uruguay";
$countryPop{UZB} = 33580650;
$countryName{UZB} = "Uzbekistan";
$countryPop{VUT} = 299882;
$countryName{VUT} = "Vanuatu";
$countryPop{VEN} = 28515829;
$countryName{VEN} = "Venezuela";
$countryPop{VNM} = 96462106;
$countryName{VNM} = "Vietnam";
$countryPop{VIR} = 106631;
$countryName{VIR} = "Virgin Islands (U.S.)";
$countryPop{PSE} = 4685306;
$countryName{PSE} = "West Bank and Gaza";
$countryPop{ESH} = 567402; # added, wikipedia:  https://en.wikipedia.org/wiki/Western_Sahara
$countryName{ESH} = "Western Sahara"; # added
$countryPop{YEM} = 29161922;
$countryName{YEM} = "Yemen";
$countryPop{ZMB} = 17861030;
$countryName{ZMB} = "Zambia";
$countryPop{ZWE} = 14645468;
$countryName{ZWE} = "Zimbabwe";


#$economist_name{} = "Anguilla";
#$economist_name{} = "Caribbean Netherlands";
$economist_name{BIH} = "Bosnia";
#$economist_name{} = "Ivory Coast";
$economist_name{COD} = "Congo";
$economist_name{COG} = "Congo-Brazzaville";
#$economist_name{} = "Cook Islands";
$economist_name{CPV} = "Cape Verde";
$economist_name{CUW} = "Curaçao";
$economist_name{CZE} = "Czech Republic";
#$economist_name{} = "Eritrea";
#$economist_name{} = "Falkland Islands";
$economist_name{GBR} = "Britain";
#$economist_name{} = "Guernsey";
$economist_name{GMB} = "The Gambia";
#$economist_name{} = "Jersey";
$economist_name{KOR} = "South Korea";
#$economist_name{} = "Macau";
$economist_name{MMR} = "Myanmar";
#$economist_name{} = "Montserrat";
#$economist_name{} = "Niue";
#$economist_name{} = "Pitcairn";
#$economist_name{} = "North Korea";
#$economist_name{} = "Palestinian Territories";
#$economist_name{} = "St. Helena Ascension and Tristan da Cunha";
$economist_name{STP} = "São Tomé and Príncipe";
$economist_name{SXM} = "Sint Maarten";
#$economist_name{} = "Tokelau";
$economist_name{TWN} = "Taiwan";
$economist_name{USA} = "United States";
#$economist_name{} = "Vatican";
$economist_name{VGB} = "Virgin Islands (British)";
#$economist_name{} = "Wallis and Futuna";
$economist_name{EU} = "European Union";


my %needsTotal;
$needsTotal{Australia} = "AUS";
$needsTotal{Canada} = "CAN";
$needsTotal{China} = "CHN";

my %provinceCodes;
$provinceCodes{"Australian Capital Territory"} = "AUS-ACT";
$provinceCodes{"New South Wales"} = "AUS-NSW";
$provinceCodes{"Northern Territory"} = "AUS-NT";
$provinceCodes{"Queensland"} = "AUS-QLD";
$provinceCodes{"South Australia"} = "AUS-SA";
$provinceCodes{"Tasmania"} = "AUS-TAS";
$provinceCodes{"Victoria"} = "AUS-VIC";
$provinceCodes{"Western Australia"} = "AUS-WA";

$countryName{"AUS-ACT"} = "Australian Capital Territory";
$countryPop{"AUS-ACT"} = 428100;
$countryName{"AUS-NSW"} = "New South Wales";
$countryPop{"AUS-NSW"} = 8118000;
$countryName{"AUS-NT"} = "Northern Territory";
$countryPop{"AUS-NT"} = 245600;
$countryName{"AUS-QLD"} = "Queensland";
$countryPop{"AUS-QLD"} = 5115500;
$countryName{"AUS-SA"} = "South Australia";
$countryPop{"AUS-SA"} = 1756500;
$countryName{"AUS-TAS"} = "Tasmania";
$countryPop{"AUS-TAS"} = 535500;
$countryName{"AUS-VIC"} = "Victoria";
$countryPop{"AUS-VIC"} = 6629900;
$countryName{"AUS-WA"} = "Western Australia";
$countryPop{"AUS-WA"} = 2630600;

$provinceCodes{"Alberta"} = "CAN-AB";
$provinceCodes{"British Columbia"} = "CAN-BC";
$provinceCodes{"Manitoba"} = "CAN-MB";
$provinceCodes{"New Brunswick"} = "CAN-NB";
$provinceCodes{"Newfoundland and Labrador"} = "CAN-NL";
$provinceCodes{"Northwest Territories"} = "CAN-NW";
$provinceCodes{"Nova Scotia"} = "CAN-NS";
$provinceCodes{"Ontario"} = "CAN-ON";
$provinceCodes{"Prince Edward Island"} = "CAN-PE";
$provinceCodes{"Quebec"} = "CAN-QC";
$provinceCodes{"Saskatchewan"} = "CAN-SK";
$provinceCodes{"Yukon"} = "CAN-YK";

$countryName{"CAN-AB"} = "Alberta";
$countryPop{"CAN-AB"} = 4413146;
$countryName{"CAN-BC"} = "British Columbia";
$countryPop{"CAN-BC"} = 5110917;
$countryName{"CAN-MB"} = "Manitoba";
$countryPop{"CAN-MB"} = 1377517;
$countryName{"CAN-NB"} = "New Brunswick";
$countryPop{"CAN-NB"} = 779993;
$countryName{"CAN-NL"} = "Newfoundland and Labrador";
$countryPop{"CAN-NL"} = 521365;
$countryName{"CAN-NW"} = "Northwest Territories";
$countryPop{"CAN-NW"} = 44904;
$countryName{"CAN-NS"} = "Nova Scotia";
$countryPop{"CAN-NS"} = 977457;
$countryName{"CAN-ON"} = "Ontario";
$countryPop{"CAN-ON"} = 14711827;
$countryName{"CAN-PE"} = "Prince Edward Island";
$countryPop{"CAN-PE"} = 158158;
$countryName{"CAN-QC"} = "Quebec";
$countryPop{"CAN-QC"} = 8537674;
$countryName{"CAN-SK"} = "Saskatchewan";
$countryPop{"CAN-SK"} = 1181666;
$countryName{"CAN-YK"} = "Yukon";
$countryPop{"CAN-YK"} = 41078;

# english and german
$provinceCodes{"Baden-Württemberg"} = "DEU-BW";
$provinceCodes{"Baden-Wurttemberg"} = "DEU-BW";
$provinceCodes{"Baden-Wuerttemberg"} = "DEU-BW";
$provinceCodes{"Bavaria"} = "DEU-BY";
$provinceCodes{"Bayern"} = "DEU-BY";
$provinceCodes{"Berlin"} = "DEU-BE";
$provinceCodes{"Brandenburg"} = "DEU-BB";
$provinceCodes{"Bremen"} = "DEU-HB";
$provinceCodes{"Hamburg"} = "DEU-HH";
$provinceCodes{"Hesse"} = "DEU-HE";
$provinceCodes{"Hessen"} = "DEU-HE";
$provinceCodes{"Lower Saxony"} = "DEU-NI";
$provinceCodes{"Niedersachsen"} = "DEU-NI";
$provinceCodes{"Mecklenburg-Vorpommern"} = "DEU-MV";
$provinceCodes{"North Rhine-Westphalia"} = "DEU-NW";
$provinceCodes{"Nordrhein-Westfalen"} = "DEU-NW";
$provinceCodes{"Rhineland-Palatinate"} = "DEU-RP";
$provinceCodes{"Rheinland-Pfalz"} = "DEU-RP";
$provinceCodes{"Saarland"} = "DEU-SL";
$provinceCodes{"Saxony-Anhalt"} = "DEU-ST";
$provinceCodes{"Sachsen-Anhalt"} = "DEU-ST";
$provinceCodes{"Saxony"} = "DEU-SN";
$provinceCodes{"Sachsen"} = "DEU-SN";
$provinceCodes{"Schleswig-Holstein"} = "DEU-SH";
$provinceCodes{"Thuringia"} = "DEU-TH";
$provinceCodes{"Thuringen"} = "DEU-TH";

$countryName{"DEU-SH"} = "Schleswig-Holstein";
$countryPop{"DEU-SH"} = 2896712;
$countryName{"DEU-HH"} = "Hamburg";
$countryPop{"DEU-HH"} = 1841179;
$countryName{"DEU-NI"} = "Lower Saxony";
$countryPop{"DEU-NI"} = 7982448;
$countryName{"DEU-HB"} = "Bremen";
$countryPop{"DEU-HB"} = 682986;
$countryName{"DEU-NW"} = "North Rhine-Westphalia";
$countryPop{"DEU-NW"} = 17932651;
$countryName{"DEU-HE"} = "Hessen";
$countryPop{"DEU-HE"} = 6265809;
$countryName{"DEU-RP"} = "Rhineland-Palatinate";
$countryPop{"DEU-RP"} = 4084844;
$countryName{"DEU-BW"} = "Baden-Württemberg";
$countryPop{"DEU-BW"} = 11069533;
$countryName{"DEU-BY"} = "Bavaria";
$countryPop{"DEU-BY"} = 13076721;
$countryName{"DEU-SL"} = "Saarland";
$countryPop{"DEU-SL"} = 990509;
$countryName{"DEU-BB"} = "Brandenburg";
$countryPop{"DEU-BB"} = 2511917;
$countryName{"DEU-MV"} = "Mecklenburg-Vorpommern";
$countryPop{"DEU-MV"} = 1609675;
$countryName{"DEU-SN"} = "Saxony";
$countryPop{"DEU-SN"} = 4077937;
$countryName{"DEU-ST"} = "Saxony-Anhalt";
$countryPop{"DEU-ST"} = 2208321;
$countryName{"DEU-TH"} = "Thuringia";
$countryPop{"DEU-TH"} = 2143145;
$countryName{"DEU-BE"} = "Berlin";
$countryPop{"DEU-BE"} = 3644826;

# TODO: China

my @countyList;

if ($args =~ m/(County|City|Parish|Cty|Area|Boro)/i) {
  # counties
  foreach my $arg (split(":", $args)) {
    if ($arg =~ m/^\s*([a-z -]*?)\s+(County|City|Parish|Cty|Area|Boro),\s*([a-z ]*?)\s*$/i) {
      my $state = uc $3;
      if ($state ~~ @statesandterritories) {
	$state = $stateToName{$state};
      }
      push @countyList, "$1;$state";
    }
  }
} else {
  my $i = 0;
  while ($i <= $#ARGV) {
    if ($ARGV[$i] =~ /^[A-Z][A-Z]$/i and uc $ARGV[$i] ~~ @statesandterritories) {
      push @states, uc $ARGV[$i];
    } elsif ($ARGV[$i] =~ /^NYC$/i) {
      push @countyList, "New York City;New York";
    } else {
      push @interest, $ARGV[$i];
    }
    $i++;
  }
}

# countries, foreign states
if ($#interest >= 0) {

  my $url = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv";
  local $/;   # read entire file -- FIXME: potentially memory hungry
  open (CSV, '-|', "curl --max-time 10 -s -k -L '$url'");
  my $csv = <CSV>;
  close(CSV);

  my %countrySeries;
  my @countryDataList;

  $csv =~ s/"Korea, South"/Korea/;
  $csv =~ s/Bonaire, Sint/Bonaire Sint/;

  foreach my $line (split /\n/, $csv) {
    next if $line =~ /^Province/; # header
    my @fields = split /,/, $line;

    next if $fields[0] ne "" and not defined $needsTotal{$fields[1]}; # ignore states/provinces for now TODO

    if ($fields[0] eq "") {
      foreach my $iso (keys %countryName) {
	if ($countryName{$iso} eq $fields[1]) {
	  my @cases = @fields[4 .. $#fields];
	  $countrySeries{$iso} = clone(\@cases);
	  push @countryDataList, $fields[1];
	}
      }
    } else {

      my $province = $fields[0];

      push @countryDataList, $fields[0];

      if (defined $needsTotal{$fields[1]}) {
	my @provinceCases = @fields[4 .. $#fields];
	my $provincecode = $provinceCodes{$fields[0]};
	$countrySeries{$provincecode} = clone(\@provinceCases);

	my $iso = $needsTotal{$fields[1]};
	if (not defined $countrySeries{$iso}) {
	  $countrySeries{$iso} = clone(\@provinceCases);
	  push @countryDataList, $fields[1];
	} else {
	  my @prevData = @{clone($countrySeries{$iso})};
	  for (my $n = 0; $n <= $#provinceCases ; $n++) {
	    $prevData[$n] = $prevData[$n] + $provinceCases[$n];
	  }
	  $countrySeries{$iso} = clone(\@prevData);
	}
      }
    }
  }

  # add german state data
  # TODO: be smarter about when to get this data
  my $url = "https://raw.githubusercontent.com/jgehrcke/covid-19-germany-gae/master/cases-rki-by-state.csv";
  my %posmap;
  my %statemap;
  local $/ = "\n";   # read by line
  open (CSV, '-|', "curl --max-time 10 -s -k -L '$url'");
  while (<CSV>) {
    s/,DE-/,DEU-/g if /^time_iso/;
    my @row = split /,/;
    if (/^time_iso/) { # header row
      for (my $n = 0; $n <= $#row; $n++) {
	#print "$n: $row[$n]\n";
	$posmap{$n} = $row[$n];
	$statemap{$row[$n]} = $n;
      }
    } else {
      for (my $n = 1; $n <= $#row; $n++) {
	if (not defined $countrySeries{$posmap{$n}}) {
	  my @cases = ( $row[$n] );
	  $countrySeries{$posmap{$n}} = clone(\@cases);
	  push @countryDataList, $countryName{$posmap{$n}};
	} else {
	  my @prevData = @{clone($countrySeries{$posmap{$n}})};
	  push @prevData, $row[$n];
	  $countrySeries{$posmap{$n}} = clone(\@prevData);
	}
      }
    }
  }
  close(CSV);

  # vaccinations per country
  $url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv";
  my %peopleVax;
  my %peopleFullVax;
  my %lastVax;
  my %lastFullVax;

  open(CSV, '-|', "curl --max-time 10 -s -k '$url'");
  binmode(CSV, ":utf8");
  while (<CSV>) {
    chomp;

    my (undef, $vax_iso_cc, $date, undef, $ppl_vax, $ppl_full_vax) = split /,/;

    next if $vax_iso_cc eq "iso_code"; #header row

    #normalize
    $ppl_vax = 0 if not defined $ppl_vax;
    $ppl_full_vax = 0 if not defined $ppl_full_vax;
    $ppl_vax = $lastVax{$vax_iso_cc} if $ppl_vax == 0 and defined $lastVax{$vax_iso_cc};
    $ppl_full_vax = $lastFullVax{$vax_iso_cc} if $ppl_full_vax == 0 and defined $lastFullVax{$vax_iso_cc};

    $lastVax{$vax_iso_cc} = $ppl_vax if $ppl_vax > 0;
    $lastFullVax{$vax_iso_cc} = $ppl_full_vax if $ppl_full_vax > 0;

    $peopleVax{"${vax_iso_cc}_${date}"} = $ppl_vax;
    $peopleFullVax{"${vax_iso_cc}_${date}"} = $ppl_full_vax;
    #  print "$vax_iso_cc $date $ppl_vax $ppl_full_vax\n";
  }
  close(CSV);

  # get excess death estimate from The Economist
  $url = "https://raw.githubusercontent.com/TheEconomist/covid-19-the-economist-global-excess-deaths-model/main/output-data/output-for-interactive/by_location_per_100k_cumulative.csv";

  open(CSV, '-|', "curl --max-time 10 -s -k '$url'");
  binmode(CSV, ":utf8");
  my %excess_deaths_per100k;
  while (<CSV>) {
    chomp;
    s/"Caribbean Netherlands \(Bonaire, Sint Eustatius and Saba\)"/Caribbean Netherlands/;
    my ($cname, $date, $est, undef, undef, undef, undef, $official) = split /,/;
    $excess_deaths_per100k{$cname} = join(',', ($date, $est, $official));
    #print "$cname => ($date, $est, $official)\n";
  }
  close(CSV);

  foreach my $i (@interest) {
    my @cases = undef;
    my @deaths = undef;
    my @vax = undef;
    my @fullVax = undef;
    my $match = undef;
    my $searchname = $i;
    my $isocode = undef;

    $i = "GBR" if $i eq "UK";

    if (defined $countryName{uc $i}) {
      $searchname = $countryName{uc $i};
      $isocode = uc $i;
    }

    if ($searchname ~~ @countryDataList) {
      $match = $searchname;
    } else {
      foreach my $ctry (@countryDataList) {
	if (lc $searchname eq lc $ctry or (length $searchname > 3 and $ctry =~ m/$searchname/i )) {
	  $match = $ctry;
	  last;
	}
      }
      foreach my $prov (keys %provinceCodes) {
	if (lc $searchname eq lc $prov) {
	  $match = $prov;
	  $isocode = $provinceCodes{$prov};
	  last;
	}
      }
      if (not defined $match) {
	foreach my $prov (keys %provinceCodes) {
	  if (length $searchname > 3 and $prov =~ m/$searchname/i) {
	    $match = $prov;
	    $isocode = $provinceCodes{$prov};
	    last;
	  }
	}
      }
    }

    if (not defined $match) {
      print "not found: $i\n";
      next;
    }
    if (not defined $isocode) {
      foreach my $k (keys %countryName) {
	if ($countryName{$k} eq $match) {
	  $isocode = $k;
	}
      }
    }
    #print "$isocode\n";
    #print "$match\n";
    if (not defined $isocode or $isocode eq "") {
      print "not found: $searchname\n";
      last;
    }

    @cases = @{$countrySeries{$isocode}};

    foreach my $k (sort keys %peopleVax) {
      if (rindex($k, $isocode, 0) == 0) { # if $k startswith $isocode
	#print "$isocode: $k $peopleVax{$k}\n";
	push @vax, $peopleVax{$k};
	push @fullVax, $peopleFullVax{$k};
      }
    }

    my $sum = 0;
    my @weeklyCasesPerCap;
    for (my $n = $#cases; $n > 0; $n--) {
      my $delta = 0;
      $delta = $cases[$n] - $cases[$n-1];
      $sum += $delta;
      #print "$sum\n";
      if ($n < $#cases and ($#cases - $n) % 7 == 6) {
	my $rate = $sum / ($countryPop{$isocode} / 100000.0);
	#print "$sum -> $rate\n";
	unshift(@weeklyCasesPerCap, $rate);   # insert at front
	$sum = 0;
      }
    }
    if ($sum > 0) {  # any leftover
      unshift(@weeklyCasesPerCap, $sum / ($countryPop{$isocode} / 100000.0));
      $sum = 0;
    }

    my @last52weeks = @weeklyCasesPerCap[$#weeklyCasesPerCap-52 .. $#weeklyCasesPerCap];
    my @result = seriesToSparkLine(\@last52weeks, 1, 0);
    my $min = $result[0];
    my $max = $result[1];
    my @spark = @result[2 .. $#result];
    my $sparkline = optimizeIrcColor(join("", @spark));
    printf "%s weekly chart: %s: max %s weekly cases per 100k pop in last 52 weeks\n", $isocode, $sparkline, colorByRate(sprintf("%0.1f", $max), $max);

    my @last31cases = @cases[$#cases-31 .. $#cases];
    my @last30caseDeltas;
    my @last30caseDeltasPerCap;
    for (my $i = 1; $i <= $#last31cases; $i++) {
      $last30caseDeltas[$i-1] = $last31cases[$i] - $last31cases[$i - 1];
      $last30caseDeltasPerCap[$i-1] = $last30caseDeltas[$i-1] / ($countryPop{$isocode} / 100000.0);
    }

    #@result = seriesToSparkLine(\@last30caseDeltas, 0, 0);  # ignored
    my $dailyCaseMin = min(@last30caseDeltas);
    my $dailyCaseMax = max(@last30caseDeltas);

    @result = seriesToSparkLine(\@last30caseDeltasPerCap, 1, 1);
    $min = $result[0];
    $max = $result[1];
    @spark = @result[2 .. $#result];
    $sparkline = optimizeIrcColor(join("", @spark));
    printf "%s last 30d: %s: %s-%s daily new cases", $isocode, $sparkline, commify($dailyCaseMin), commify($dailyCaseMax);

    my $sevenDayTotal = sum(@last30caseDeltas[$#last30caseDeltas-6 .. $#last30caseDeltas]);
    my $sevenDayPerCap = $sevenDayTotal / ($countryPop{$isocode} / 100000.0);
    printf("; %s total for last 7d (%s per 100k over 7d)\n", commify($sevenDayTotal), colorByRate(sprintf("%0.1f", $sevenDayPerCap), $sevenDayPerCap));

    if ($#vax > 0) {
      # daily initial vaccinations - per country
      my @last31vax;
      if ($#vax > 31) {
	@last31vax = @vax[$#vax-31 .. $#vax];
      } else {
	@last31vax = @vax[0 .. $#vax];
      }
      my @last30vaxDeltas;
      for (my $i = 1; $i <= $#last31vax; $i++) {
	$last30vaxDeltas[$i-1] = $last31vax[$i] - $last31vax[$i - 1];
	$last30vaxDeltas[$i-1] = 0 if not defined $last31vax[$i] or not defined $last31vax[$i-1];
      }

      #my $dailyVaxMin = min(@last30vaxDeltas);
      #my $dailyVaxMax = max(@last30vaxDeltas);

      my $sum = 0;
      for (my $i = 6; $i >= 0; $i--) {
	$sum += $last30vaxDeltas[$#last30vaxDeltas-$i];
      }
      my $avg = round($sum / 7.0);
      #print "$sum - avg: $avg new vax/day\n";
      my $percap = $sum / ($countryPop{$isocode} / 100000.0);
      my $popvax = ($vax[$#vax] / $countryPop{$isocode}) * 100.0;

      #@result = seriesToSparkLine(\@last30vaxDeltas, 0, 0);
      #$min = $result[0];
      #$max = $result[1];
      #@spark = @result[2 .. $#result];
      #printf "%s ppl newly vaxxed last 30d: %s: %s-%s daily (avg %s/day in last 7d); %s weekly newly vaxxed per 100k pop; %s of pop. partially vaxxed\n", $isocode, join("", @spark), commify($dailyVaxMin), commify($dailyVaxMax), commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));
      printf "%s avg newly vaxxed %s/day in last 7d; %s weekly newly vaxxed per 100k pop; %s of pop. partially vaxxed\n", $isocode, commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));
    }

    if ($#fullVax > 0) {
      # daily full vaccinations - per country
      my @last31vax;
      if ($#vax > 31) {
	@last31vax = @fullVax[$#fullVax-31 .. $#fullVax];
      } else {
	@last31vax = @fullVax[0 .. $#fullVax];
      }
      my @last30vaxDeltas;
      for (my $i = 1; $i <= $#last31vax; $i++) {
	$last30vaxDeltas[$i-1] = $last31vax[$i] - $last31vax[$i - 1];
	$last30vaxDeltas[$i-1] = 0 if not defined $last31vax[$i] or not defined $last31vax[$i-1];
      }

      #my $dailyVaxMin = min(@last30vaxDeltas);
      #my $dailyVaxMax = max(@last30vaxDeltas);

      $sum = 0;
      for (my $i = 6; $i >= 0; $i--) {
	$sum += $last30vaxDeltas[$#last30vaxDeltas-$i];
      }
      my $avg = round($sum / 7.0);
      #print "$sum - avg: $avg new vax/day\n";
      my $percap = $sum / ($countryPop{$isocode} / 100000.0);
      my $popvax = ($fullVax[$#fullVax] / $countryPop{$isocode}) * 100.0;

      #@result = seriesToSparkLine(\@last30vaxDeltas, 0, 0);
      #$min = $result[0];
      #$max = $result[1];
      #@spark = @result[2 .. $#result];
      #printf "%s ppl fully vaxxed last 30d: %s: %s-%s daily (avg %s/day in last 7d); %s weekly fully vaxxed per 100k pop; %s of pop. fully vaxxed\n", $isocode, join("", @spark), commify($dailyVaxMin), commify($dailyVaxMax), commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));
      printf "%s avg fully vaxxed %s/day in last 7d; %s weekly fully vaxxed per 100k pop; %s of pop. fully vaxxed\n", $isocode, commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));

    }

    my $key = $countryName{$isocode};
    $key = $economist_name{$isocode} if not defined $excess_deaths_per100k{$key};
    #print "$isocode $countryName{$isocode} $excess_deaths_per100k{$key}\n";
    if (defined $key and defined $excess_deaths_per100k{$key}) {
      my ($date, $est, $official) = split /,/, $excess_deaths_per100k{$key};

      if (defined $est and $est > 0.0 and (not defined $official or (defined $official and $official eq "NA"))) {
	# estimate, no official
	print $isocode, " est. ", bold(nearest(0.1, $est)), " excess deaths per 100k pop\n";
      } elsif (defined $est and $est > 0.0 and defined $official and $official ne "NA" and $est > $official) {
	# estimate > official
	print $isocode, " est. ", bold(nearest(0.1, $est)), " excess deaths per 100k pop";
	print " (", nearest(0.1, $est/$official), "x official death rate)\n";
      } elsif (defined $est and $est > 0.0 and defined $official and $official ne "NA" and $est < $official) {
	# estimate < official
	print $isocode, " official deaths ", bold(nearest(0.1, $official)), " per 100k pop\n";
      }
      # no estimate, no official -- fall through
    }
  }
}

# states
if ($#states >= 0) {
  my @names;
  foreach my $s (@states) {
    push @names, $stateToName{$s};
  }

  my %caseTotals;
  my %deathTotals;
  my %peopleVax;
  my %peopleFullVax;

  my $prevCases = undef;
  my $prevDeaths = undef;
  my $last = 0; #debug

  my $url = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv";
  open(CSV, '-|', "curl --max-time 10 -s -k '$url'");
  binmode(CSV, ":utf8");
  while (<CSV>) {
    chomp;
    my ($date, $state, $fips, $cases, $deaths) = split /,/;
    if ($state ~~ @names) {
      $caseTotals{"${state}_${date}"} = $cases;
      $deathTotals{"${state}_${date}"} = $deaths;
      #print "${state}_${date} = ", $cases - $last, "\n";
      $last = $cases;
    }
  }
  close(CSV);

  # vaccinations per state
  $url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv";
  open(CSV, '-|', "curl --max-time 10 -s -k '$url'");
  binmode(CSV, ":utf8");
  my %lastVax;
  my %lastFullVax;
  while (<CSV>) {
    chomp;
    my ($date, $place, undef, undef, $ppl_vax, undef, undef, $ppl_full_vax) = split /,/;
    $place =~ s/New York State/New York/;

    #normalize
    $ppl_vax = 0 if not defined $ppl_vax;
    $ppl_full_vax = 0 if not defined $ppl_full_vax;
    $ppl_vax = $lastVax{$place} if $ppl_vax == 0 and defined $lastVax{$place};
    $ppl_full_vax = $lastFullVax{$place} if $ppl_full_vax == 0 and defined $lastFullVax{$place};

    $lastVax{$place} = $ppl_vax if $ppl_vax > 0;
    $lastFullVax{$place} = $ppl_full_vax if $ppl_full_vax > 0;

    if ($place ~~ @names) {
      $peopleVax{"${place}_${date}"} = $ppl_vax;
      $peopleFullVax{"${place}_${date}"} = $ppl_full_vax;
      #print "$place $date $ppl_vax $ppl_full_vax\n";
    }
  }
  close(CSV);

  foreach my $s (@states) {
    my $n = $stateToName{$s};
    my @cases = undef;
    my @deaths = undef;
    my @vax = undef;
    my @fullVax = undef;
    foreach my $k (sort keys %caseTotals) {
      if (rindex($k, $n, 0) == 0) { # if $k startswith $n
	#print "$n: $k $caseTotals{$k}\n";
	push @cases, $caseTotals{$k};
	push @deaths, $deathTotals{$k};
	push @vax, $peopleVax{$k};
	push @fullVax, $peopleFullVax{$k};
      }
    }

    if ($#cases == 0) {
      print "$s not found\n";
      next;
    }

    my $sum = 0;
    my @weeklyCasesPerCap;
    for (my $n = $#cases; $n > 0; $n--) {
      my $delta = 0;
      $delta = $cases[$n] - $cases[$n-1];
      $sum += $delta;
      #print "$sum\n";
      if ($n < $#cases and ($#cases - $n) % 7 == 6) {
	my $rate = $sum / ($statePop{$s} / 100000.0);
	#print "$sum -> $rate\n";
	unshift(@weeklyCasesPerCap, $rate);   # insert at front
	$sum = 0;
      }
    }
    if ($sum > 0) {  # any leftover
      unshift(@weeklyCasesPerCap, $sum / ($statePop{$s} / 100000.0));
      $sum = 0;
    }

    my @last52weeks = @weeklyCasesPerCap[$#weeklyCasesPerCap-52 .. $#weeklyCasesPerCap];
    my @result = seriesToSparkLine(\@last52weeks, 1, 0);
    my $min = $result[0];
    my $max = $result[1];
    my @spark = @result[2 .. $#result];
    my $sparkline = optimizeIrcColor(join("", @spark));
    printf "%s weekly chart: %s: max %s weekly cases per 100k pop in last 52 weeks\n", $s, $sparkline, colorByRate(sprintf("%0.1f", $max), $max);


    my @last31cases = @cases[$#cases-31 .. $#cases];
    my @last30caseDeltas;
    my @last30caseDeltasPerCap;
    for (my $i = 1; $i <= $#last31cases; $i++) {
      $last30caseDeltas[$i-1] = $last31cases[$i] - $last31cases[$i - 1];
      $last30caseDeltasPerCap[$i-1] = $last30caseDeltas[$i-1] / ($statePop{$s} / 100000.0);
    }

    my $dailyCaseMin = min(@last30caseDeltas);
    my $dailyCaseMax = max(@last30caseDeltas);

    @result = seriesToSparkLine(\@last30caseDeltasPerCap, 1, 1);
    $min = $result[0];
    $max = $result[1];
    @spark = @result[2 .. $#result];
    $sparkline = optimizeIrcColor(join("", @spark));

    printf "%s last 30d: %s: %s-%s daily new cases", $s, $sparkline, commify($dailyCaseMin), commify($dailyCaseMax);

    my $sevenDayTotal = sum(@last30caseDeltas[$#last30caseDeltas-6 .. $#last30caseDeltas]);
    my $sevenDayPerCap = $sevenDayTotal / ($statePop{$s} / 100000.0);
    printf("; %s total for last 7d (%s per 100k over 7d)\n", commify($sevenDayTotal), colorByRate(sprintf("%0.1f", $sevenDayPerCap), $sevenDayPerCap));

    # compute weekly percent positives
    ## FIXME not used currently
    my $url = "https://api.covidtracking.com/v1/states/" . lc $s. "/daily.csv";
    my $positiveDeltaPosition = -1;
    my $testDeltaPosition = -1;
    my @dailyPctPositives;
    my %dailyNewPositives;
    my %dailyNewTests;
    open(CSV, '-|', "curl --max-time 10 -s -k '$url'");
    binmode(CSV, ":utf8");
    while (<CSV>) {
      chomp;
      my @row = split /,/;
      if (/^date/) {
	for (my $i = 0; $i <= $#row; $i++) {
	  $positiveDeltaPosition = $i if $row[$i] eq "positiveIncrease";
	  $testDeltaPosition = $i if $row[$i] eq "totalTestResultsIncrease";
	}
      }
      if (/^[0-9]/) {
	my $date = $row[0];
	my $posDelta = $row[$positiveDeltaPosition];
	my $testDelta = $row[$testDeltaPosition];
	my $pctPositive = 0;
	$pctPositive = ($posDelta / ($testDelta * 1.0)) * 100.0 if $testDelta > 0;
	#$pctPositive = nearest(0.1, $pctPositive);
	#print "$date $pctPositive% :: $posDelta / $testDelta\n";
	$dailyNewPositives{$date} = $posDelta;
	$dailyNewTests{$date} = $testDelta;
	unshift(@dailyPctPositives, $pctPositive);
      }
    }
    close(CSV);

    my $sumTests = 0;
    my $sumPositives = 0;
    my $i = 0;
    my @weeklyPctPositives;
    foreach my $d (sort {$b <=> $a} keys %dailyNewPositives) {  # descending
      $sumTests += $dailyNewTests{$d};
      $sumPositives += $dailyNewPositives{$d};
      if (++$i == 7) {
	my $weeklyPos = 0;
	$weeklyPos = ($sumPositives / $sumTests) * 100;
	#printf("$d: weekly positives: %0.1f%%\n", $weeklyPos);
	unshift(@weeklyPctPositives, $weeklyPos);
	$i = 0;
      }
    }
    my @result = seriesToSparkLine(\@weeklyPctPositives, 2, 0);
    my $min = $result[0];
    my $max = $result[1];
    my @spark = @result[2 .. $#result];
    my $sparkline = optimizeIrcColor(join("", @spark));
#    # dubious data? FIXME
#    printf "%s weekly percent positive %s: max %s weekly; last %s weekly\n", $s, $sparkline,
#      colorByPctPos(sprintf("%0.1f%%", $max), $max),
#      colorByPctPos(sprintf("%0.1f%%", $weeklyPctPositives[$#weeklyPctPositives]), $weeklyPctPositives[$#weeklyPctPositives]);


    # daily initial vaccinations
    my @last31vax = @vax[$#vax-31 .. $#vax];
    my @last30vaxDeltas;
    for (my $i = 1; $i <= $#last31vax; $i++) {
      $last30vaxDeltas[$i-1] = $last31vax[$i] - $last31vax[$i - 1];
      $last30vaxDeltas[$i-1] = 0 if not defined $last31vax[$i] or not defined $last31vax[$i-1];
    }

    #my $dailyVaxMin = min(@last30vaxDeltas);
    #my $dailyVaxMax = max(@last30vaxDeltas);

    my $sum = 0;
    for (my $i = 6; $i >= 0; $i--) {
      $sum += $last30vaxDeltas[$#last30vaxDeltas-$i];
    }
    my $avg = round($sum / 7.0);
    #print "$sum - avg: $avg new vax/day\n";
    my $percap = $sum / ($statePop{$s} / 100000.0);
    my $popvax = ($vax[$#vax] / $statePop{$s}) * 100.0;

    #@result = seriesToSparkLine(\@last30vaxDeltas, 0, 0);
    #$min = $result[0];
    #$max = $result[1];
    #@spark = @result[2 .. $#result];
    #printf "%s ppl newly vaxxed last 30d: %s: %s-%s daily (avg %s/day in last 7d); %s weekly newly vaxxed per 100k pop; %s of pop. partially vaxxed\n", $s, join("", @spark), commify($dailyVaxMin), commify($dailyVaxMax), commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));
    printf "%s avg newly vaxxed %s/day in last 7d; %s weekly newly vaxxed per 100k pop; %s of pop. partially vaxxed\n", $s, commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));

    # daily full vaccinations
    @last31vax = @fullVax[$#vax-31 .. $#vax];
    @last30vaxDeltas;
    for (my $i = 1; $i <= $#last31vax; $i++) {
      $last30vaxDeltas[$i-1] = $last31vax[$i] - $last31vax[$i - 1];
      $last30vaxDeltas[$i-1] = 0 if not defined $last31vax[$i] or not defined $last31vax[$i-1];
    }

    #$dailyVaxMin = min(@last30vaxDeltas);
    #$dailyVaxMax = max(@last30vaxDeltas);

    $sum = 0;
    for (my $i = 6; $i >= 0; $i--) {
      $sum += $last30vaxDeltas[$#last30vaxDeltas-$i];
    }
    $avg = round($sum / 7.0);
    #print "$sum - avg: $avg new vax/day\n";
    $percap = $sum / ($statePop{$s} / 100000.0);
    $popvax = ($fullVax[$#fullVax] / $statePop{$s}) * 100.0;

    #@result = seriesToSparkLine(\@last30vaxDeltas, 0, 0);
    #$min = $result[0];
    #$max = $result[1];
    #@spark = @result[2 .. $#result];
    #printf "%s ppl fully vaxxed last 30d: %s: %s-%s daily (avg %s/day in last 7d); %s weekly fully vaxxed per 100k pop; %s of pop. fully vaxxed\n", $s, join("", @spark), commify($dailyVaxMin), commify($dailyVaxMax), commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));
    printf "%s avg fully vaxxed %s/day in last 7d; %s weekly fully vaxxed per 100k pop; %s of pop. fully vaxxed\n", $s, commify($avg), bold(commify(sprintf("%0.1f", $percap))), bold(sprintf("%0.1f%%", $popvax));


  }

}

# US counties
if ($#countyList >= 0) {

  my %ctypop;
  my $ctyfile = dirname(realpath(__FILE__)) . "/2019-popestimate-us-counties.csv";
  if (not -e $ctyfile) {
    print "error: unable to find $ctyfile\n";
    exit 0;
  }
  open(CTYPOP, "<", $ctyfile);
  while (<CTYPOP>) {
    next if /^STNAME/;
    my ($st, $cty, $census, $est) = split /,/;
    $cty =~ s/\s*(County|City|Parish|Borough|Census Area|City and Borough|Municipality)\s*$//i unless $cty eq "New York City";
    $ctypop{lc "${st}_$cty"} = $est;
  }
  close(CTYPOP);

  my $url = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv";
  my %caseTotals;
  my $last = 0; #debug

  open(HTTP, '-|', "curl --max-time 30 -s -k -L '$url'");
  while (<HTTP>) {
    my ($date,$county,$state,$fips,$cases,$deaths) = split /,/;
    $county =~ s/\s*\<(County|City|Parish|Borough|Census Area|City and Borough|Municipality)\>\s*$//i unless $county eq "New York City";
    for my $c (@countyList) {
      my ($cty, $st) = split(";", $c);
      $cty = "New York City" if lc $cty eq "new york";
      #print "$state $county :: ${st}_${cty}_${date} = $cases\n" if $county =~ m/bergen/i;
      #print "$state $county :: ${st}_${cty}_${date} = ", $cases - $last, "\n" if $county =~ m/bergen/i;
      #$last = $cases if $county =~ m/bergen/i;
      if ((lc $cty eq lc $county) and (lc $st eq lc $state)) {
	$caseTotals{"${st}_${cty}_${date}"} = $cases;
      }
    }
  }
  close(HTTP);

  $url = "https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_county_condensed_data";
  my %cty_vaxx;
  open(HTTP, '-|', "curl --max-time 10 -s -k -L '$url'");
  local $/;   # read entire file -- FIXME: potentially memory hungry
  my $json = <HTTP>;
  close(HTTP);
  if (not $json =~ /^\s*{/) {
    print "error while retrieving data: $json\n";
    exit 0;
  }
  my $j = decode_json($json);
  if (defined $j->{vaccination_county_condensed_data}) {
    foreach my $rec (@{$j->{vaccination_county_condensed_data}}) {
      my $cty = lc $rec->{County};
      $cty =~ s/\s*(county|city|parish|area|boro)\s*$//i;
      my $st = $rec->{StateName};
      $st =~ s/\s*$//;
      my $dt = $rec->{Date};
      my $num_full_vax = $rec->{Series_Complete_Yes};
      $cty_vaxx{"${st}_${cty}"} = $num_full_vax;
      #print "$st $cty => $num_full_vax\n";
    }
  }

  for my $c (@countyList) {
    my ($cty, $st) = split(";", $c);
    $cty = "New York City" if lc $cty eq "new york";
    my @cases = undef;
    my @deaths = undef;

    my $n = lc "${st}_${cty}_";
    foreach my $k (sort keys %caseTotals) {
      if (rindex(lc $k, $n, 0) == 0) { # if $k startswith $n
	#print "$n: $caseTotals{$k}\n";
	push @cases, $caseTotals{$k};
      }
    }

    if ($#cases == 0) {
      print "$cty, $st: not found\n";
      next;
    }


    #print "st: $st\n";
    #print "cty: $cty\n";

    my $pop = $ctypop{lc "${st}_$cty"};
    #print "pop: $pop\n";

    my $sum = 0;
    my @weeklyCasesPerCap;
    for (my $n = $#cases; $n > 0; $n--) {
      my $delta = 0;
      $delta = $cases[$n] - $cases[$n-1];
      $sum += $delta;
      #print "$sum\n";
      if ($n < $#cases and ($#cases - $n) % 7 == 6) {
	my $rate = $sum / ($pop / 100000.0);
	#print "$sum -> $rate\n";
	unshift(@weeklyCasesPerCap, $rate);   # insert at front
	$sum = 0;
      }
    }
    if ($sum > 0) {  # any leftover
      unshift(@weeklyCasesPerCap, $sum / ($pop / 100000.0)); # FIXME
      $sum = 0;
    }

    my @last52weeks = @weeklyCasesPerCap[$#weeklyCasesPerCap-52 .. $#weeklyCasesPerCap];
    my @result = seriesToSparkLine(\@last52weeks, 1, 0);
    my $min = $result[0];
    my $max = $result[1];
    my @spark = @result[2 .. $#result];
    my $sparkline = optimizeIrcColor(join("", @spark));
    printf "%s, %s weekly chart: %s: max %s weekly cases per 100k pop in last 52 weeks\n", $cty, $st, $sparkline, colorByRate(sprintf("%0.1f", $max), $max);

    my @last31cases = @cases[$#cases-31 .. $#cases];
    my @last30caseDeltas;
    my @last30caseDeltasPerCap;
    for (my $i = 1; $i <= $#last31cases; $i++) {
      $last30caseDeltas[$i-1] = $last31cases[$i] - $last31cases[$i - 1];
      $last30caseDeltasPerCap[$i-1] = $last30caseDeltas[$i-1] / ($pop / 100000.0);
    }

    my $dailyCaseMin = min(@last30caseDeltas);
    my $dailyCaseMax = max(@last30caseDeltas);

    @result = seriesToSparkLine(\@last30caseDeltasPerCap, 1, 1);
    $min = $result[0];
    $max = $result[1];
    @spark = @result[2 .. $#result];
    $sparkline = optimizeIrcColor(join("", @spark));

    printf "%s, %s last 30d: %s: %s-%s daily new cases", $cty, $st, $sparkline, commify($dailyCaseMin), commify($dailyCaseMax);

    my $sevenDayTotal = sum(@last30caseDeltas[$#last30caseDeltas-6 .. $#last30caseDeltas]);
    my $sevenDayPerCap = $sevenDayTotal / ($pop / 100000.0);
    printf("; %s total for last 7d (%s per 100k over 7d)\n", commify($sevenDayTotal), colorByRate(sprintf("%0.1f", $sevenDayPerCap), $sevenDayPerCap));

    my $lcty = lc $cty;
    my $full_vaxxed = $cty_vaxx{"${st}_${lcty}"};
    my $unknowncty_vaxxed = $cty_vaxx{"${st}_unknown county"};

    my $st_pop = undef;
    foreach my $k (keys %stateToName) {
      if ($stateToName{$k} eq $st) {
	$st_pop = $statePop{$k};
	last;
      }
    }
    #print "$unknowncty_vaxxed; $st_pop;\n";

    if (defined $full_vaxxed) {
      printf("%s, %s: %s%% of pop. fully vaccinated", $cty, $st, bold(nearest(0.1, $full_vaxxed * 100.0 / $pop)));
      printf(" (vax for %s%% of state pop. unallocated to a county)",
	nearest(0.1, $unknowncty_vaxxed * 100.0 / $st_pop)) if defined $st_pop and defined $unknowncty_vaxxed;
      print "\n";
    }

  }
}

# world totals
if ($#interest == -1 and $#states == -1 and $#countyList == -1) {
  my $url = "https://www.worldometers.info/coronavirus/";
  my $date;
  my ($incases, $indeaths, $inrecov) = (0, 0, 0);
  my ($c, $d, $r) = (0,0,0);
  system("curl --max-time 10 -s -k '$url' > /tmp/c19-temp.html");
  open(HTTP, '-|', "elinks --dump /tmp/c19-temp.html");
  binmode(HTTP, ":utf8");
  while (<HTTP>) {
    s/^\s*//;
    s/\[\d+\]//g;

    $date = "$1z" if /Last updated: (.*) GMT/;

    $incases = 1 if /Coronavirus Cases:/;
    $c = $1 if /^\s*([0-9,]+)\s*$/ and $incases == 1;
    $c =~ s/,//g if $incases == 1;
    $incases = 0 if $c != 0;

    $indeaths = 1 if /Deaths:/;
    $d = $1 if /^\s*([0-9,]+)\s*$/ and $indeaths == 1;
    $d =~ s/,//g if $indeaths == 1;
    $indeaths = 0 if $d != 0;

    $inrecov = 1 if /Recovered:/;
    $r = $1 if /^\s*([0-9,]+)\s*$/ and $inrecov == 1;
    $r =~ s/,//g if $inrecov == 1;
    $inrecov = 0 if $r != 0;
  }
  close(HTTP);

  my $pct = sprintf("%0.1f", ($d/($d+$r)*100.0));
  print "As of $date, there are ", yellow(commify($c)), " confirmed cases and ",
    red(commify($d)), " deaths, with ", lightblue(commify($r)),
    " recovered. Death rate ", red("$pct%"), " of resolved cases.\n";
}

sub seriesToSparkLine {
  my $arrayref = shift;
  my $color = shift;
  my $daily = shift;
  my @series = @$arrayref;
  my $min = 999999999999;
  my $max = -999999999999;
  my @result;

  foreach my $e (@series) {
    $min = $e if $e < $min and $e > 0;
    $max = $e if $e > $max and $e > 0;
  }

  push @result, ($min, $max);

  foreach my $v (@series) {
    my $chr = valToBlock($v, $min, $max);
    $v = $v * 7.0 if $daily != 0;
    $chr = colorByRate($chr, $v) if $color == 1;
    $chr = colorByPctPos($chr, $v) if $color == 2;
    push @result, $chr;
  }

  return @result;
}

# relative to min/max
sub valToBlock {
  my $v = shift;
  my $min = shift;
  my $max = shift;
  my $step = ($max - $min)/8;
  my $chr = " ";

  if ($v < $min) {
    $chr = "\xA0"; # NBSP
  } elsif ($v <= ($min + ($step * 1))) {
    $chr = "▁";
  } elsif ($v <= ($min + ($step * 2))) {
    $chr = "▂";
  } elsif ($v <= ($min + ($step * 3))) {
    $chr = "▃";
  } elsif ($v <= ($min + ($step * 4))) {
    $chr = "▄";
  } elsif ($v <= ($min + ($step * 5))) {
    $chr = "▅";
  } elsif ($v <= ($min + ($step * 6))) {
    $chr = "▆";
  } elsif ($v <= ($min + ($step * 7))) {
    $chr = "▇";
  } elsif ($v <= ($min + ($step * 8))) {
    $chr = "█";
  } else {
    $chr = "↑";
  }
  return $chr;
}

sub colorByRate {
  my $str = shift;
  my $rate = shift;

  if ($rate < 5.0) {
    return green($str);
  } elsif ($rate < 25.0) {
    return lightgreen($str);
  } elsif ($rate < 38.0) {
    return yellow($str);
  } elsif ($rate < 50.0) {
    return darkYellow($str);
  } elsif ($rate < 100.0) {
    return darkRed($str);
  } elsif ($rate < 325.0) {
    return red($str);
  } elsif ($rate >= 325.0) {
    return magenta($str);
  }
  return $str;
}

sub colorByPctPos {
  my $str = shift;
  my $rate = shift;

  if ($rate < 0.5) {
    return green($str);
  } elsif ($rate < 1.0) {
    return lightgreen($str);
  } elsif ($rate < 3.0) {
    return yellow($str);
  } elsif ($rate < 5.0) {
    return darkYellow($str);
  } elsif ($rate < 10.0) {
    return darkRed($str);
  } else {
    return red($str);
  }
  return $str;
}
