#!/usr/bin/perl
#
# US National debt, updated daily
#
# 2-clause BSD license.
# Copyright (c) 2018, 2020, 2021 molo1134@github. All rights reserved.

use strict;
use utf8;
use feature 'unicode_strings';
binmode(STDOUT, ":utf8");

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Util;

use JSON qw( decode_json );
use Math::Round;

my $url = "https://www.treasurydirect.gov/NP_WS/debt/feeds/recent";
#my $url = "https://treasurydirect.gov/NP/debt/rss";
my ($date, $public, $intra, $total);


open (HTTP, '-|', "curl -H 'Accept: application/rss+xml' --max-time 10 -L -k -s '$url'");
while (<HTTP>) {
  chomp;
  if (not $date and m|<title>Debt to the Penny for ([0-9/]+)</title>|i) {
    $date = $1;
  }
  if (m|<content:encoded>(.*)</content:encoded>|i) {
    my $tmp = decodeEntities($1),"\n";
    # <em>Debt Held by the Public:</em> 15,449,788,829,355.28<br /><em>Intragovernmental Holdings:</em> 5,690,264,848,112.51<br /><em>Total Public Debt Outstanding:</em> 21,140,053,677,467.79
    if (not $public and
	$tmp =~ m|Debt Held by the Public:</em>\s*([0-9,.]+)<|i) {

      $public = $1;
    }
    if (not $intra and
	$tmp =~ m|Intragovernmental Holdings:</em>\s*([0-9,.]+)<|i) {

      $intra = $1;
    }
    if (not $total and
	$tmp =~ m|Total Public Debt Outstanding:</em>\s*([0-9.,]+)\s*$|i) {

      $total = $1;
    }

  }
}
close HTTP;

my $url = "https://www.census.gov/popclock/data/population.php/us";
local $/;   # read entire file -- FIXME: potentially memory hungry
open (JSON, '-|', "curl --max-time 10 -s -k -L $url");
my $json = <JSON>;
close(JSON);
my $j = decode_json($json) or die "parse error: $json\n";

my $pop = $j->{us}->{population};

my $numtotal = $total;
$numtotal =~ s/,//g;

my $percap = nearest(0.01, $numtotal / $pop);
my $avg_household_size = 2.52; # TODO would like to get a data source
my $avg_hh_debt = nearest(0.01, $percap * $avg_household_size);

#print "$date $total $public $intra\n";
print "As of $date, the total federal public US debt is USD\$ $total"
  if defined $date and defined $total;
printf "; per-capita debt is \$%s; debt per average household is \$%s", commify($percap), commify($avg_hh_debt)
  if defined $percap;
print "\n";

