#!/usr/bin/perl -w

# Convert a string to mocking spongebob-style text
#
# Turns this:
# Guess I'll just have to play with my new icom gear
#
# Into this:
# GuEsS i'Ll JuSt HaVe To PlAy WiTh My NeW iCoM gEaR
#
# translation code from
# https://stackoverflow.com/questions/28124600/alternate-between-upper-and-lowercase-perl

use strict;
use warnings;

sub periodic {
  my @subs = @_;
  my $i = 0;

  return sub {
    $i = 0 if $i > $#subs;
    return $subs[$i++]->(@_);
  };
}

my $mystring = join(" ", @ARGV);

my $f = periodic(
  sub { uc pop },
  sub { lc pop },
);

$mystring =~ s/([a-z])/ $f->($1) /egi;
print $mystring, "\n";
