#!/usr/bin/perl
# countdown to US President inauguration
#
# 2-clause BSD license.
# Copyright (c) 2020 molo1134@github. All rights reserved.

use strict;
use DateTime;
use POSIX;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Util;

my $d1 = DateTime->now;
my ($curryear, $currmon, $currdate) = split / /, strftime("%Y %m %d", gmtime($d1->epoch()));

my $potusyear = $curryear;
while (($potusyear % 4) != 1) {
  $potusyear++;
}

my $d2 = DateTime->new(
    year       => $potusyear,
    month      => 01,
    day        => 20,
    hour       => 17,  # UTC
    minute     => 00,
    second     => 00,
);

my $dur = $d2->epoch() - $d1->epoch();

if ($dur < 0) {
	print "\"The peaceful transfer of power is what will separate our country from every other country in the world.\" -- George Washington  https://i.imgur.com/4k9kQan.jpg\n";
	exit 0;
}

my $m = floor($dur / (30 * 24 * 60 * 60));
my $d = floor($dur % (30 * 24 * 60 * 60) / (24 * 60 * 60));
my $h = floor($dur % (24 * 60 * 60) / (60 * 60));
my $min = ($dur / 60) % 60;
my $sec = $dur % 60;

print "Inauguration countdown! ";
print "$m month, " if $m == 1;
print "$m months, " if $m > 1;
print "$d day, " if $d == 1;
print "$d days, " if $d > 1;
print "$h hours, $min min, $sec sec\n";

