#!/usr/bin/perl

# earthquake data for qrmbot
# written by aa4jq

use strict;
use utf8;
use feature 'unicode_strings';
binmode(STDOUT, ":utf8");

use DateTime;
use URI::Escape;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));

my @line;
my $f = 0;

if ($ARGV[0] =~ /about/i){
    print "Returns top 5 strongest M 2.5+ earthquakes over the last 24 hours.\n";
    print "Data provided by USGS, https://earthquake.usgs.gov\n";
    exit 0;
}

# all magnitude 2.5+ quakes in the last 24 hours

my $url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson";

print "Largest 2.5+ earthquakes of the last 24 hours:\n";

open(HTTP, '-|', "curl -s -L --insecure '$url' | jq -c '.features[] | [.properties.time,.properties.title]' | sort -rn -k2 | head -5");

binmode(HTTP, ":utf8");
while ( my $line = <HTTP>) {

    chomp;

    my ($time, $event) = split(/,/,$line,2);

    $time =~ s/\[//;
    $event =~ s/"\]//;
    $event =~ s/"//;

    if ($time ne "null") {
        my $utc = DateTime->from_epoch(epoch=>($time/1000),time_zone=> "UTC");
        print $utc->hms . " UTC " . $event;
        $f = 1;
    }
}
close(HTTP);

if ($f == 0){
    print "No earthquakes M2.5+ in the last hour.\n";
}

exit 0;
