#!/usr/bin/perl -w
# Calculate satellite passes.  2-clause BSD license.

# Copyright 2018 /u/molo1134. All rights reserved.

use strict;
use utf8;
use feature 'unicode_strings';
use Astro::Coord::ECI;
use Astro::Coord::ECI::TLE;
use Astro::Coord::ECI::TLE::Set;
#use Astro::Coord::ECI::Utils qw{deg2rad rad2deg};
use Math::Trig;
use POSIX qw(strftime);
binmode(STDOUT, ":utf8");

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;
use Location;

my $tleurl="http://www.amsat.org/amsat/ftp/keps/current/nasabare.txt";

# potential changes:
# 1) parameter for number of passes / length of time?
# 2) parameter for minimum elevation (default 5 deg)?

my %aliases = (
  # lowercase key
  "ao-7" => "AO-07",
  "ariss" => "ISS",
  "dauriadx1" => "DAURIA DX 1",
  "dauria-dx-1" => "DAURIA DX 1",
  "fu3" => "FIREBIRD FU3",
  "firebirdfu3" => "FIREBIRD FU3",
  "firebird-fu3" => "FIREBIRD FU3",
  "fu4" => "FIREBIRD FU4",
  "firebirdfu4" => "FIREBIRD FU4",
  "firebird-fu4" => "FIREBIRD FU4",
  "estar-2" => "e-st\@r-II",
  "estar2" => "e-st\@r-II",
  "estar-ii" => "e-st\@r-II",
  "e-star-ii" => "e-st\@r-II",
  "nodes1" => "NODES 1",
  "nodes-1" => "NODES 1",
  "nodes2" => "NODES 2",
  "nodes-2" => "NODES 2",
  "lapan-a3" => "Lapan A3",
  "alsat-1n" => "AlSat 1N",
  "alsat1n" => "AlSat 1N",
  "tancredo1" => "Tancredo 1",
  "tancredo-1" => "Tancredo 1",
);

my $username = $ENV{'USER'} || $ENV{'USERNAME'} || getpwuid($<);

# change this to 0 to always exit with success
our $exitnonzeroonerror = 1;
$exitnonzeroonerror = 0 if $username eq 'eggdrop';

if ($#ARGV < 0 || length($ARGV[0]) == 0) {
  #print "usage: $0 <sat> <grid>|<qth> [<elev>ft|<elev>m]\n";
  print "usage: $0 <sat> <qth>|<grid>\n" if $username ne "eggdrop";
  print "usage: !sat <sat> <qth>|<grid>\n" if $username eq "eggdrop";
  exit $exitnonzeroonerror;
}

# eggdrop doesn't split args on spaces
@ARGV=split(' ', join(' ',@ARGV));

my $query = "";
my $sat = undef;
my $elev_m = "0";
my $i = 0;
while ($i <= $#ARGV) {
  if ( $ARGV[$i] =~ /^([0-9]+)(ft|m)/ ) {
    if ($2 eq "m") {
      $elev_m = $1;
    } elsif ($2 eq "ft") {
      $elev_m = $1 * 0.3048;  # feet to meters
    }
  } elsif (!defined($sat)) {
    $sat = $ARGV[$i];
  } else {
    $query .= " " unless $i == 1;
    $query .= $ARGV[$i];
  }
  $i++;
}
if ($query =~ /^(.+)\s+[0-9.-]+,[0-9.-]+/) {
  # if both a text parameter and a geo coord, use the text (for irc)
  $query = $1;
}
#print "query: $query\n";
#print "$elev_m\n";

if (length($query) == 0 && $sat ne "list") {
  print "usage: $0 <sat> <qth>|<grid>\n" if $username ne "eggdrop";
  print "usage: !sat <sat> <qth>|<grid>\n" if $username eq "eggdrop";
  exit $exitnonzeroonerror;
}

my ($lat, $lon) = (0, 0);

if ($sat ne "list") {
  my $geo = argToCoords($query);
  if (!defined($geo)) {
    print "error: not found: $query\n";
    exit $exitnonzeroonerror;
  }
  ($lat, $lon) = split(',', $geo) if $query ne '';
  #print ("$lat, $lon\n");
}

my $now = time();

my $sta = Astro::Coord::ECI->universal($now)->
  geodetic(deg2rad($lat), deg2rad($lon), $elev_m / 1000);  #kilometers
$sta->set(refraction => 0);
$sta->universal($now);

my @data;
open(TLE, '-|', "curl --max-time 5 -s $tleurl");
while (<TLE>) {
  push (@data, $_);
}
close(TLE);

#my $seen = 0;
#open(TLE, '-|', "curl -s http://www.amsat.org/amsat/ftp/keps/current/nasa.all");
#while (<TLE>) {
#  if (/TO ALL RADIO AMATEURS/) {
#    $seen = 1;
#    next;
#  }
#  if (/^\s*$/) {
#    next;
#  }
#  if (/^\/EX/) {
#    next;
#  }
#  push (@data, $_) if $seen == 1;
#}
#close(TLE);

#print("records: $#data\n");
my @elements = Astro::Coord::ECI::TLE::Set->aggregate(
		  Astro::Coord::ECI::TLE->parse(@data));
#print("records: $#data\n");

# only passes for the next 24h
my $finish = $now + (1 * 86400);

my $found = 0;

if (defined($aliases{$sat})) {
  $sat = $aliases{lc($sat)};
}

my @passes;
my @sats;
foreach my $tle (@elements) {
  my $name = $tle->get('name');
  $name =~ s/ /-/g;
  push(@sats, $name);
  if (lc($name) eq lc($sat)) {
    #print "$name\n";
    $tle->validate($now, $finish) or next;
    $found = 1;
    #print $tle->tle_verbose(), "\n";
    #print $name = $tle->get('tle'), "\n";
    #print "doing passes..\n";
    $tle->set('pass_threshold', deg2rad(5)); # minimum peak elevation
    $tle->set('visible', 0);
    $tle->set('horizon', 0);
    push(@passes, $tle->pass($sta, $now, $finish));
  }
}

if (lc($sat) eq "list") {
  my $list = join(" ", @sats);
  my $frag = undef;
  my $limit = 68;
  $limit = 400 if $username eq "eggdrop";
  do {
    # line wrap
    $frag = undef;
    if (length $list > $limit) {
      $list =~ s/^(.{$limit}.*?)\s(.*)$/$1/;
      $frag = $2;
      print $list, "\n";
      $list = $frag;
    }
  } while defined ($frag);
  print $list, "\n";
  exit 0;
}

if ($found == 0) {
  print "satellite not found: $sat\n";
  exit $exitnonzeroonerror;
}

#print("passes: $#passes\n");

#print "      Date/Time          Satellite        Elevation  Azimuth Event\n";

if ($#passes < 0) {
  print "$sat: no passes found within 24h\n";
  exit $exitnonzeroonerror;
}

my $numpasses = 3;
$numpasses = 100 if $username ne "eggdrop";
my $first = 1;

foreach my $pass (sort {$a->{time} <=> $b->{time}} @passes) {
  #print "\n";
  foreach my $event (@{$pass->{events}}) {

    if ($event->{event} eq "rise") {
      if ($first == 1) {
	printf("%s @%s: ",
	  bold($event->{body}->get('name')),
	  coordToGrid($lat, $lon));
	$first = 0;
      }
      print "\n  " if $username ne "eggdrop";
      print green("AOS"),
	    strftime(" %Y-%m-%d ", gmtime($event->{time})),
	    bold(strftime("%H:%Mz", gmtime($event->{time}))),
	    sprintf(" az %d°; ", rad2deg($event->{azimuth}));
    }

    if ($event->{event} eq "max") {
      print "max el ", bold(sprintf("%d°", rad2deg($event->{elevation})));
      printf(" az %d°; ", rad2deg($event->{azimuth}));
    }

    if ($event->{event} eq "set") {
      print red("LOS");
      printf(" %s az %d°",
	bold(strftime("%H:%Mz", gmtime($event->{time}))),
	rad2deg($event->{azimuth}));

      --$numpasses;
      print "\n" if $numpasses == 0;
      print " ‖ " if $numpasses > 0 && $username eq "eggdrop";
      exit 0 if $numpasses == 0;
    }

    # not reached
    #printf("%s %-15s %9.1f %9.1f %-5s\n",
    #  scalar gmtime($event->{time}),
    #  $event->{body}->get('name'),
    #  rad2deg($event->{elevation}),
    #  rad2deg($event->{azimuth}),
    #  $event->{event}) if 0;
    #
    #if ($event->{event} eq "set") {
    #  exit 0;
    #}
  }
}
print "\n";

