#!/usr/bin/perl
# countdown to spooky
# based on christmas script
#
# 2-clause BSD license.
# Copyright (c) 2019 OliverUK. All rights reserved.
# Copyright (c) 2019, 2020 molo1134@github. All rights reserved.

use strict;
use DateTime;
use POSIX;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Util;

my $d1 = DateTime->now;
my ($curryear, $currmon, $currdate) = split / /, strftime("%Y %m %d", gmtime($d1->epoch()));
#print "$curryear, $currmon, $currdate\n";
#print "$thxyear, $thxmon, $thxdate\n";


my $spookyyear = $curryear;
$spookyyear-- if $currmon == 1 and $currdate < 7;

my $d2 = DateTime->new(
    year       => $spookyyear,
    month      => 10,
    day        => 30,
    hour       => 23,
    minute     => 59,
    second     => 59,
);

my $dur = $d2->epoch() - $d1->epoch();

if ($dur < 0) {
	print "🎃 🎃 🎃 Happy Halloween everyone! https://media2.giphy.com/media/l3vRfhFD8hJCiP0uQ/giphy.gif\n";
	exit 0;
}

my $m = floor($dur / (30 * 24 * 60 * 60));
my $d = floor($dur % (30 * 24 * 60 * 60) / (24 * 60 * 60));
my $h = floor($dur % (24 * 60 * 60) / (60 * 60));
my $min = ($dur / 60) % 60;
my $sec = $dur % 60;

print "Spooky countdown! ";
print "$m month, " if $m == 1;
print "$m months, " if $m > 1;
print "$d day, " if $d == 1;
print "$d days, " if $d > 1;
print "$h hours, $min min, $sec sec\n";
