#!/usr/bin/perl
# winadmin countdown by nickenzi; based on brexit countdown which was contributed by OliverUK
#
# 2-clause BSD license.
# Copyright (c) 2019, 2020 molo1134@github. All rights reserved.

use strict;
use DateTime;
use POSIX;

my $d1 = DateTime->now;
my $d2 = DateTime->new(
    year       => 2025,
    month      => 6,
    day        => 17,
    hour       => 9,
    minute     => 0,
    second     => 0,
);

my $dur = $d2->epoch() - $d1->epoch();

if ($dur < 0) {
	print "Goodbye, winadmin! https://i.imgur.com/ZzISerM.gif\n";
	exit 0;
}

my $m = floor($dur / (30 * 24 * 60 * 60));
my $d = floor($dur % (30 * 24 * 60 * 60) / (24 * 60 * 60));
my $h = floor($dur % (24 * 60 * 60) / (60 * 60));
my $min = ($dur / 60) % 60;
my $sec = $dur % 60;

print "The clock is ticking for winadmin! ";
print "$m month, " if $m == 1;
print "$m months, " if $m > 1;
print "$d day, " if $d == 1;
print "$d days, " if $d > 1;
print "$h hours, $min min, $sec sec\n";
