#!/usr/bin/perl -w
# Retrieve solar x-ray data.  2-clause BSD license.

# Copyright 2018 /u/molo1134. All rights reserved.

use strict;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;

my $url = "https://services.swpc.noaa.gov/products/latest-xray-event.json";
my %data;

open (HTTP, '-|', "curl -L -k -s $url");
while (<HTTP>) {
  my @entries = split /,/;
  foreach my $e (@entries) {
    $e =~ s/^{//;
    $e =~ s/}$//;
    #print "$e\n";
    if ($e =~ /^\s*"([^"]+)":"([^"]+)"\s*$/) {
      $data{$1} = $2;
      #print "$1 = $2\n";
    }
  }
}
close(HTTP);

if (not defined($data{current_time})) {
  print "not found.\n";
  exit 0;
}

my $curr_time = $data{current_time};
$curr_time =~ s/:00$//;
my $max_time = $data{max_time};
$max_time =~ s/:00$//;

print "Xray status: ". colorize($data{current_class}) . " at ${curr_time}z; recent flare: " . colorize($data{max_class}) . " at ${max_time}z\n";

#print colorize("M1.1"), "\n";
#print colorize("M5.1"), "\n";
#print colorize("X1.1"), "\n";
#print colorize("X9.1"), "\n";
#print colorize("X10.1"), "\n";
#print colorize("X20.1"), "\n";

sub colorize {
  my $s = shift;
  $s = green($s) if $s =~ /^[ABC]/;
  $s = yellow($s) if $s =~ /^M/;
  $s = red($s) if $s =~ /^X[0-9][^0-9]/;
  $s = lightblue($s) if $s =~ /^X[0-9]{2}/;
  return $s;
}
