#!/usr/bin/perl -w
# Retrieve solar x-ray data.

# 2-clause BSD license.
# Copyright (c) 2018, 2020, 2021 molo1134@github. All rights reserved.

use strict;

use File::Basename;
use Cwd 'realpath';
use lib dirname(realpath(__FILE__));
use Colors;

my $url = "https://services.swpc.noaa.gov/json/goes/primary/xray-flares-latest.json";
my %data;

open (HTTP, '-|', "curl --max-time 10 -L -k -s $url");
while (<HTTP>) {
  my @entries = split /,/;
  foreach my $e (@entries) {
    $e =~ s/^{//;
    $e =~ s/}$//;
    #print "$e\n";
    if ($e =~ /^\s*"([^"]+)":\s+"([^"]+)"\s*$/) {
      $data{$1} = $2;
      #print "$1 = $2\n";
    }
  }
}
close(HTTP);

if (not defined($data{end_time})) {
  print "not found.\n";
  exit 0;
}

my $curr_time = $data{end_time};
$curr_time = $data{begin_time} if not defined $curr_time or $curr_time eq "Unk";
$curr_time =~ s/:00$// if defined $curr_time;
my $max_time = $data{max_time};
$max_time =~ s/:00$//;

print "Xray status: ". colorize($data{current_class}) . " at ${curr_time}";
print "; recent flare: " . colorize($data{max_class}) . " at ${max_time}" if defined $data{max_class};
print "\n";

#print colorize("M1.1"), "\n";
#print colorize("M5.1"), "\n";
#print colorize("X1.1"), "\n";
#print colorize("X9.1"), "\n";
#print colorize("X10.1"), "\n";
#print colorize("X20.1"), "\n";

sub colorize {
  my $s = shift;
  return $s if not defined $s;
  $s = green($s) if $s =~ /^[ABC]/;
  $s = yellow($s) if $s =~ /^M/;
  $s = red($s) if $s =~ /^X[0-9][^0-9]/;
  $s = magenta($s) if $s =~ /^X[0-9]{2}/;
  return $s;
}
